bluewave-labs/Checkmate

Server/controllers/monitorController.js, Server/db/MongoDB.js, Server/service/jobQueue.js, Server/service/networkService.js
Insert checks into DB on monitor status update
Moved logic for cascading delete to `monitorController`.  Checks must be deleted here _after_ the queue is emptied, or there may be an incomplete job left in the queue that is carreid out after the `monitor` is deleted.  If this occurs, a dangling check without an associated monitor will be left in the database.  Now we are deleting associated checks only after the queue is drained, so this bug should be resolved.
Added JSDoc to network service
=> Checks now inserted into db during monitor status check, reslovles #141

README.md, Server/db/MongoDB.js, Server/models/Check.js
* `getMonitorsByUserId` now returns `Monitor` with all its associated `Check` objects attached in ascending order (oldest first).
* `getMonitorById` also returns `Check` with the same sort order
Added a Time To Live field to the `Check` object with default time of 30 days.  Checks older than that will be automatically purged from the DB.  The duration of TTL can be discussed
=> Added checks to monitors for getMonitorsById and getMonitorsByUserId.…, resolves #155

Client/src/Components/ProgressBars/index.css, Client/src/Components/ProgressBars/index.jsx, Client/src/Components/TabPanels/ProfileSettings/ProfilePanel.jsx, Client/src/Components/TextFields/Image/index.jsx, Client/src/Pages/Demo/Demo.jsx, Client/src/Utils/Theme.js
Design is not final, just wanted to get everyone's input on it.
For testing, the loading states are currently managed using a timeout mechanism but will swap to redux once everything is streamlined. The progress bar is managed through `setUploadProgress`, a `useState` hook, which increments linearly at fixed intervals (`x` ms) using `setInterval` . This is likely to be changed in the future to properly and accurately reflect progress. This could be done using redux through the `auth` slice or setting up a separate slice. I would prefer the latter just to keep `auth` as clean as possible, especially if we end up using different image renders, and for editting the picture. What do you all think?
Stuff not implemented yet: 
- File (type/size) restrictions.
- Connect to redux store.
- Edit …
=> Client side upload picture, #193

Client/src/Pages/Login/index.css
Per issue  #193  : The password input field styling appears to be broken.  
The .css file for this component did not include any styling for the password input. I've added this to conform to the same styling as the Email input field and tested locally.  
I note that this issue also seems to have been previously fixed, then reverted again in a closed PR, #205
=> fix: add css for password input field

Client/src/App.jsx, Client/src/Components/MonitorTable/index.jsx
Clicking on a monitor from the list now takes you to the details page with the monitor ID passed along
=> Update route to pass monitor ID to details component, #120

Client/src/Components/TabPanels/Account/PasswordPanel.jsx, Client/src/Components/TextFields/Password/PasswordTextField.jsx, Client/src/Features/Auth/authSlice.js, Client/src/Validation/validation.js
Connected password form to redux. There are sill some checks to be done. Currently any error from the request will display under the `Password` text field, where we're specifically looking for the "Incorrect password" (403) error only. The easy solution would be to simply check for `action.payload.msg === "Incorrect password"` but that doesn't feel right. Any thoughts?
=> Connected password form to redux, resolves #214

Client/src/Components/BasicTable/index.jsx, Client/src/Pages/Monitors/Details/index.jsx
Data in `BasicTable` can now be displayed in reverse order by adding `reverse` prop
=> Feat/table order, resolves #403

Docker/docker-compose.yaml
Bind port 80 to 5173 so you can just visit `<host>` instead of `<host>:5173` when deployed
=> Update docker compose to bind port 80

Client/src/Components/NavBar/index.jsx
authState.user.role can now be safely accessed if authState.user is undefined preventing the includes error.
=> Fixed error that occurs when authState.user is undefined

Server/controllers/monitorController.js, Server/service/jobQueue.js
Updating a job in the JobQueue requires first removing the active job and then readding it with new parameters.
BullMQ `removeRepeatable` requires the exact same parameters that were provided to create a job in order to delete it.
The parameters used to create the job are the monitors ID and `interval` key, as such we need to get the unmodified monitor prior to update in order to remove the job or else the `interval` may change, making the job inaccessible.
Also fixed an error in accessing monitor's `_id` field
=> JobQueue was not deleting jobs correctly due to incorrect  lookup

Server/controllers/monitorController.js, Server/db/mongo/modules/monitorModule.js
A user is able to modify recipients for notifications when they edit a Monitor.
Easiest way of handling this is to drop all notifications currently associated with that Monitor and then add their new ones.
Implemented as such, can revisit if not performant
=> Notifications removed and readded on monitor edit

Server/service/jobQueue.js
When a monitor is created, immediately add a non-repeateable job to the queue so we have data right away.
=> Add instant check at create monitor time, resolves #516

Client/src/Components/BasicTable/index.css, Client/src/Components/NavBar/index.jsx, Client/src/Pages/Monitors/index.css, Client/src/Pages/Monitors/index.jsx, Client/src/Pages/PageSpeed/CreatePageSpeed/index.css, Client/src/Pages/PageSpeed/CreatePageSpeed/index.jsx, Client/src/Pages/PageSpeed/index.css, Client/src/Pages/PageSpeed/index.jsx
There was too much whitespace so I limited the form width to `1000px`. The alternative would be to match the `CreateMonitor` page design, since the two use the same components.
=> Updated create page speed monitor page

Client/src/Components/Charts/MonitorDetailsAreaChart/index.jsx
As checks are ordered oldest -> newest the removed `break` would have been called as soon as there is a check older than the set limit, which stops the chart from populating
=> Removed logical error in check filter for monitor chart, resolves #541

Client/src/Pages/Monitors/index.css, Client/src/Pages/Monitors/index.jsx
I opted with displaying some fallback UI instead of hard redirecting the user to `/monitors/create`.
Resolves #240
=> Added fallback UI in case the user has no monitors created

Client/src/Pages/Monitors/Details/PaginationTable/index.jsx, Client/src/Pages/Monitors/Details/index.jsx, Server/controllers/checkController.js, Server/db/mongo/MongoDB.js, Server/db/mongo/modules/checkModule.js, Server/utils/dataUtils.js, Server/validation/joi.js
Checks are now fetched from the Checks endpoint instead in a separate API calls
Checks are paginated, and only those needed are returned
I implemented a new table rarther than try to cram the more compled pagination logic into BasicTable, I don't think there are any real benefits to be reaped by trying to shoehorn the logic in.
@danielcj2 I'm affraid I'm once again going to have to ask you to style a table :joy:  Many thanks in advance :pray:
=> Fix/be/monitor data pagination, also resolves #567

Server/db/mongo/modules/monitorModule.js
=> Minor bugfixes

Client/src/Pages/Incidents/IncidentTable/index.jsx, Client/src/Pages/Incidents/index.jsx
There was a double rendering happening in `IncidentTable`, I've added a check condition to stop the extra rendering and fixed the depndency array as well.
I believe this resovles the skeleton issue, can you comfirm @danielcj2 ?
=> Stop double rendering, add monitors to useEffect dependency array, #586

Client/src/Pages/Incidents/IncidentTable/index.jsx, Client/src/Pages/Monitors/Details/PaginationTable/index.jsx
=> Added pagination resets, resolve #588

Client/src/Pages/Auth/Register/Register.jsx, Client/src/Pages/Auth/index.css, Client/src/Pages/Incidents/IncidentTable/index.jsx, Client/src/Pages/Incidents/index.css
=> Added fallback UI when there are no incidents recorded

Client/src/Pages/Auth/CheckEmail.jsx, Client/src/Pages/Auth/ForgotPassword.jsx, Client/src/Pages/Auth/NewPasswordConfirmed.jsx, Client/src/Pages/Auth/index.css
Looks much the same as the other auth pages.
=> Password confirmed page

Server/db/mongo/modules/monitorModule.js
=> Fixed spelling error, moved incident calculation to correct location

Server/models/Check.js
=> Server status update bug fixed, simplified email notification

Client/src/Features/Auth/authSlice.js, Client/src/Features/PageSpeedMonitor/pageSpeedMonitorSlice.js, Client/src/Features/UptimeMonitors/uptimeMonitorsSlice.js
```
{
success: false,
msg: "error message"
}
```
Resolves #616
=> fix: if no response from server reject with proper payload format, resolves #616

Client/src/Pages/Monitors/index.jsx
=> fix: disabled open site option for ping type monitors

Client/package-lock.json, Client/package.json
=> Bump axios and recharts

Server/service/networkService.js
If a job is left in the queue for some reason and it's associated monitor is deleted then `null` will be returned when a monitor is queried.  
Adding null check allows for graceful failure here
=> Add null monitor check to Network Service

Client/src/Components/BasicTable/index.jsx
This PR fixes some minor issues with the `BasicTable` component
=> Add safe accesss default for rowsPerPage, add proptypes

Client/src/Components/BasicTable/index.jsx, Client/src/Components/TabPanels/Account/TeamPanel.jsx, Client/src/Pages/Monitors/Details/index.jsx, Client/src/Pages/Monitors/index.jsx
This PR resolves the bug with `rowsPerPage` in the UI state being set using the path.
=> Add table prop to BasicTable to specify table name, resolves #707

Client/src/Features/PageSpeedMonitor/pageSpeedMonitorSlice.js, Client/src/Pages/PageSpeed/CreatePageSpeed/index.jsx
This PR updates Pagespeed thunk and associated methods to use teamId
=> Update pagespeed to use teamId

Client/src/Features/UptimeMonitors/uptimeMonitorsSlice.js, Client/src/Pages/Monitors/Configure/index.jsx, Client/src/Pages/Monitors/Configure/skeleton.jsx, Client/src/Pages/Monitors/Home/index.jsx, Client/src/Utils/NetworkService.js, Server/controllers/monitorController.js, Server/db/mongo/modules/monitorModule.js, Server/routes/monitorRoute.js, Server/utils/messages.js, Server/validation/joi.js
This PR implements pause functionality for monitors
=> Add pause routes and controller, implement functionality

Server/db/mongo/modules/monitorModule.js, Server/index.js, Server/service/networkService.js
This PR fixes unsafe access to a `monitor`'s `notification` field.
The issue presents itself if there is a discrepancy beween the job in the Redis database and the data in the Mogno dataabse.
=> Add safety check for monitor

Client/src/Pages/Monitors/Home/host.jsx
This PR udpates host proptypes as the `percentage` prop has changed from `number` to `string` with the implementation of uptime percentage.
=> fix host proptypes

Server/openapi.json
Create `openapi.json` under the Server directory. Yaml is easy to read and write for me but to make it compatible with **SwaggerHub** and **SwaggerUIExpress** I choose the json.
```js
const openapi = require("./openapi.json")
```
It's not a complete fix but still associated with #581
=> chore: create openapi.json with openapi 3.1.0 format

Client/src/Components/Label/index.jsx, Client/src/Pages/Monitors/Configure/index.jsx, Client/src/Pages/Monitors/Details/index.jsx, Client/src/Pages/Monitors/Details/skeleton.jsx, Client/src/Pages/Monitors/Home/monitorData.jsx
This PR adds pending states and messages to a number of pages
=> Add pending state to monitors and config screens, resolves #771, resolves #766

Server/controllers/authController.js
This PR fixes the delete user method
=> fix delete user method

Docker/docker-compose.yaml, Docker/mongo/init/create_users.js, Docker/mongoDB.Dockerfile, README.md
This PR addresses lack of security for MongoDB, revealed by recent ransom request
This shouldn't affect developers on their local development instances, only those that are deployed using docker compose
=> Add env files, update config

Client/src/Pages/Monitors/Home/MonitorTable/index.jsx, Client/src/Pages/Monitors/utils.jsx, Client/src/Pages/PageSpeed/Configure/index.jsx, Client/src/Pages/PageSpeed/Details/index.jsx, Client/src/Pages/PageSpeed/Details/skeleton.jsx, Client/src/Pages/PageSpeed/card.jsx, Client/src/Pages/PageSpeed/index.jsx
This PR implements monitor states for Pagespeed pages
=> Implement monitor states for Pagespeed pages

Client/src/App.jsx, Client/src/Pages/Incidents/index.jsx, Client/src/Pages/Monitors/Home/actionsMenu.jsx
This PR enables the "Incidents" action menu item
=> Enabled incident in actions menu, set selected monitor in Incidents page

Server/controllers/checkController.js, Server/db/mongo/MongoDB.js, Server/db/mongo/modules/checkModule.js, Server/db/mongo/modules/monitorModule.js, Server/middleware/handleErrors.js, Server/routes/checkRoute.js, Server/utils/messages.js, Server/validation/joi.js
This PR implements the back end portion of updating checks TTL
=> Feat/be/ttl, #764

Client/src/Pages/PageSpeed/index.jsx
This PR uses the `getMonitorsByTeamId` endpoint instead of the `getMonitorsAndSummaryByTeamId` as this page now requires the latest 10 checks.
There is no need for this data to be in the redux store so local state is used.
=> Use getMonitorsByTeamId endpoint

Client/src/Pages/Incidents/index.jsx, Server/controllers/monitorController.js, Server/db/mongo/modules/monitorModule.js
This PR fixes the slow loading of the Incidents page.  The issue was I originally designed that endpoint to return checks with the monitors.  The lazy solution was to set the limit to one and only return one check, but that solution isn't sufficient when large numbers of montiors are present.  Solution is to set limit to -1 and return no checks, avoiding the `Promise.all` which runs a query for every monitor.
=> Remove checks from monitor query

Client/src/Pages/Incidents/index.jsx, Client/src/Pages/Monitors/Home/MonitorTable/index.jsx, Client/src/Pages/PageSpeed/index.jsx, Client/src/Utils/NetworkService.js, Server/db/mongo/modules/monitorModule.js, Server/validation/joi.js
This PR implements sorting and filtering for monitors
=> Feat/be/monitor sort and filter, #498, #704

Client/src/Pages/Incidents/index.jsx, Client/src/Pages/Monitors/Home/MonitorTable/index.jsx, Client/src/Pages/PageSpeed/index.jsx, Client/src/Utils/NetworkService.js, Server/db/mongo/modules/monitorModule.js, Server/validation/joi.js
This PR implements the FE side of sorting monitors
=> Feat/fe/monitor table sort, resolves #498

Client/src/Components/Inputs/Search/index.jsx, Client/src/Pages/Monitors/Home/MonitorTable/index.jsx, Client/src/Pages/Monitors/Home/index.jsx, Client/src/Utils/debounce.jsx
This PR connects the search component to the monitor table.  A request is made to the BE when the user finishes typing.  This is a compromise between making a request on every char input and searching only when a user selects a monitor.  
By waiting until the user finishes typing we can search for partial matches as opposed to full matches only if we wait until a user clicks while at the same time not producing excessive network requests by searching at every char change.
=> Connect search component to monitor table, resolves #704

Client/src/App.jsx, Client/src/Components/Sidebar/index.jsx
This PR temporarliy comments out the Maintenance Window feature
=> Remove maintenance from sidebar and comment out routes

Client/src/Pages/Monitors/Home/MonitorTable/index.jsx
This PR fixes an issue where pagination is not reset when filtering monitors.  Example:  If you are on page 3 and filter for a monitor and there are less than three pages of results an empty list will be shown as all results are on previous pages.
=> Reset pagination on filter chagne

Client/src/Components/TabPanels/Account/TeamPanel.jsx, Client/src/Features/Auth/authSlice.js, Client/src/Features/PageSpeedMonitor/pageSpeedMonitorSlice.js, Client/src/Features/UptimeMonitors/uptimeMonitorsSlice.js, Client/src/Pages/Incidents/IncidentTable/index.jsx, Client/src/Pages/Monitors/Details/PaginationTable/index.jsx, Client/src/Pages/Monitors/Details/index.jsx, Client/src/Pages/PageSpeed/Details/index.jsx, Client/src/Pages/Settings/index.jsx, Client/src/Utils/NetworkService.js, Server/routes/inviteRoute.js
This PR refactors the requests in NetwokService to use config objects instead of a list of parameters.  This increases readability as the config object has `key:value` pairs so it is clear what params are being set.
=> Refactor network service to use config objects for clarity

Client/src/Pages/Incidents/IncidentTable/index.jsx
This PR fixes an incorrectly named parameter in the Incidents page
=> userId -> teamId

Client/src/Pages/Monitors/Details/PaginationTable/index.jsx
This PR fixes a typo in the Monitor details page
=> Fix typo in monitor details page

Client/src/App.jsx, Client/src/Pages/PageSpeed/Configure/index.jsx, Client/src/Pages/PageSpeed/Details/index.jsx, Client/src/Pages/PageSpeed/index.jsx
This PR adds an `isAdmin` prop to the PageSpeed details page to allow for conditonal rendering of components that should not be shown to non-admin users.
=> Add conditional rendering to PageSpeed pages for non admin users

Docker/nginx/conf.d/default.conf
This PR adds the Bluewave Labs demo server to the Swagger server list
=> Add bluewave server to swagger config

Server/package-lock.json
Fix: #886 
The changes are the result of the `npm audit fix` command.
It's basically made the minimum upgrade to non-vulnerable versions of the npm packages.
Most of them is indirect dependency so, directly depended package(which is express in this case) upgraded to 4.21.0 automatically.
- body-parser => `1.20.3`
- path-to-regexp => `1.0.10`
- send => `0.19.0`
- express => `4.21.0`
and more
=> Resolve known security vulnerabilities via 'npm audit fix'

Client/package-lock.json
This PR bumps the following dependencies:
=> bump FE dependencies

Client/src/Features/Settings/settingsSlice.js
This PR sets the default base API url to the empty string
=> set default url to empty string

Client/src/Pages/AdvancedSettings/index.jsx, Client/src/Utils/NetworkService.js, Server/routes/settingsRoute.js
This PR removes console.log statements and removes a permission check on the `getSettings` endpoint as all verified users should have access to this endpoint
=> removed console logs, removed permission check for getting settings

Client/src/Utils/NetworkService.js
This PR adds a fallback base API URL in case the user does not specify one in initial setup.
=> Add a fallback URL

Server/openapi.json
This PR adds a config for the dist server to the OpenAPI docs
=> add distribution server option to openapi docs

Client/src/Utils/NetworkService.js
This PR fixes the logic for loading the base API url
1. ENV var
2. Settings var
3. Fallback localhost
=> Correct base URL logic

Client/src/Pages/Maintenance/index.jsx, Client/src/Pages/Monitors/Home/index.jsx
This PR allows users with the "demo" role to view and create maintenance windows.
=> Allow demo user to create maintenance windows

Server/controllers/inviteController.js, Server/routes/inviteRoute.js, Server/tests/controllers/inviteController.test.js, Server/validation/joi.js
This PR adds tests for the inviteController.  In addition it fixes some minor bugs
=> Feat/be/invite-controller-tests, #924

Client/src/Components/Inputs/Field/index.jsx
- Added the CSS to fix current password widget in light/dark mode.
=> fix: add css to fix the current password widget under account>password

Client/src/Pages/Monitors/Home/actionsMenu.jsx
This change resolves #931 by adding pause option in the actions menu on the dashboard.
=> adds pause to action menu

Server/controllers/authController.js, Server/tests/controllers/authController.test.js
This PR updates some authController tests to provide full test coverage
=> updated tests for full coverage

docs/quickstart.md, docs/users-guide/quickstart.md, guides/users-guide/quickstart.md
This PR addresses a minor typo in the code where the word "derver" was incorrectly used instead of "server." This change improves clarity and ensures consistency throughout the codebase.
Corrected the typo in the relevant files.
=> Fix Typo: "Derver" to "Server"

Client/src/Pages/Settings/index.jsx, Client/src/Utils/NetworkService.js
Fixes issue #967 
I have added the tag which will fetch the latest version of the release from the github repo and show it in the about section of settings page.
=> Added the latest repo version in about section of Settings page

Client/src/Components/BasicTable/index.css, Client/src/Components/TabPanels/Account/TeamPanel.jsx, Client/src/Pages/Incidents/index.jsx, Client/src/Pages/Maintenance/index.jsx, Client/src/Pages/Monitors/Home/index.jsx
Fixed styling of table headers of Incidents, maintenance and team table section as discussed in issue #963. Added a common class to the parent component that renders the table.
Before:
Fixed:
closes #963
=> Fix: table header - issue#963

Server/.nycrc, Server/tests/utils/dataUtils.test.js, Server/tests/utils/imageProcessing.test.js, Server/tests/utils/messages.test.js, Server/tests/utils/utils.test.js, Server/utils/dataUtils.js
This PR adds tests for util functions on the BE
=> Add tests for util functions

Server/controllers/controllerUtils.js, Server/controllers/monitorController.js, Server/package-lock.json, Server/package.json, Server/tests/controllers/controllerUtils.test.js
This PR adds `ssl-checker` back to the project, in the end it is more reliable than using TLS to fetch certificates
=> Add ssl-checker, refactor fetchMonitorCertificate

Server/service/emailService.js
This PR fixes an incorrectly resovled merge conflict
=> Fix merge conflict error

Server/db/mongo/modules/checkModule.js
This PR fixes a missing variable declartion in the `checkModule`.
This likely happened during the migration to ESM.
=> Added missing var declaration

Docker/dev/build_images.sh, Server/controllers/authController.js
This PR refactors the Docker build script to:
Reduce redundancy using an array for Dockerfiles.
Add error handling to stop on failed builds.
Improve script readability and maintainability.
=> Optimize Docker Build Script for Maintainability and Error Handling

Client/src/Pages/AdvancedSettings/index.jsx, Client/src/Pages/Maintenance/CreateMaintenance/index.jsx, Client/src/Validation/error.js, Client/src/Validation/validation.js
Add validation to advanced settings page
- Extract buildErrors and hasValidationErrors to error.js file
- Add advanced settings validation rule
- Apply  advanced settings validation rule in field change and form submission
Below is the screen recording of the validation :
[Screencast from 2024-10-18 14-07-59.webm](https://github.com/user-attachments/assets/5715c760-1aee-4857-8d3a-a4beddfc7745)
=> FE - Advanced Settings Page Validation and Error Handling

Server/db/models/HardwareCheck.js
This PR adds a mongoDB model for hardware monitoring
This model is based on data models provided by server monitoring agent developer @mertssmnoglu :
```jsonc
{
"physical_core": integer, // Physical cores
"logical_core":  integer, // Logical cores aka Threads
"frequency":     integer, // Frequency in mHz
"temperature":   null,    // WIP
"free_percent":  null,    // WIP
"usage_percent": null     // WIP
}
```
```jsonc
{
"total_bytes":     integer, // Total space in bytes
"available_bytes": integer, // Available space in bytes
"used_bytes":      integer, // Used space in bytes      //* Total - Free - Buffers - Cached
"usage_percent":   float    // Usage Percent            //* (Used / Total) * 100.0
}
```
```jsonc
{
"read_speed_bytes":  integer, // WIP
"write_speed_bytes": integer, // WIP …
```
=> feat/be/hardware-checks-model references #985

Server/db/models/Monitor.js, Server/db/mongo/MongoDB.js, Server/db/mongo/modules/hardwareCheckModule.js, Server/service/networkService.js, Server/tests/services/networkService.test.js
This PR implements creating a hardware check monitor with associated hardware checks
=> feat/be/create-hardware-monitor, references #985

Client/.eslintrc.cjs, Server/index.js
This PR just corrects a rule that was bringing more trouble than good. 
This is the rule, and we do not need it because the workaround is much easier and readable.
https://kamrutkar.hashnode.dev/unescaped-html-entities-in-jsx-reactno-unescaped-entities
=> chore: changing rule on eslint

Client/src/Components/Sidebar/index.jsx
Let me know if I need to make further changes. 
I apologize for taking so long. Still can't figure out the installation (stuck on the .env variables), I think it's my laptop. 
If testing is necessary, could someone else do it?
=> Add link to logo

Client/src/Components/Dialog/genericDialog.jsx
Fixes #1027 
The problem was that the default behaviour of the Material UI Modal Component (used in GenericDialog component) was leading the propogation of the event . So I explicitly defined that on click, the event should not propogate.
=> Fixed the modal redirect bug

Client/src/App.jsx, Client/src/Features/UI/uiSlice.js
-> Used window.matchMedia API to get the user's theme preference to solve issue #1026
=> Added User theme(Light/Dark) preference detection

Server/service/networkService.js, Server/service/statusService.js
This PR refactors the `requestPagespeed` method of the `NetworkService` class.
The method was identical to `requestHttp` except for request URL, so it duplicated most of requestHttp's code.
=> Feat/be/refactor request pagespeed, resolves #1085

Server/db/mongo/modules/monitorModule.js, Server/db/mongo/modules/recoveryModule.js, Server/db/mongo/modules/userModule.js
This PR makes some minor changes to DB modules to improve readabiltiy
=> Minor refactoring in DB modules for readability

Server/db/mongo/modules/monitorModule.js
This PR fixes a typo in the monitor type lookup of monitorModule
=> Fix typo in monitor type lookup

Server/.nycrc, Server/controllers/monitorController.js, Server/db/mongo/MongoDB.js, Server/db/mongo/modules/checkModule.js, Server/db/mongo/modules/monitorModule.js, Server/openapi.json, Server/routes/monitorRoute.js, Server/tests/controllers/monitorController.test.js, Server/tests/db/checkModule.test.js, Server/tests/db/monitorModule.test.js, Server/tests/services/statusService.test.js
This PR implements the feature requested in discussion #1115
It also adds a missing test case for `statusService` and updates test runner configuration to run DB tests
=> Feat/be/uptime percentage stats, references #1115

Server/tests/db/monitorModule.test.js
This PR adds some missing test cases for the monitorModule, discovered because of recent pagespeed bug
=> Add missing test cases for pagespeed and hardware monitor types

Server/db/models/Monitor.js, Server/index.js, Server/package-lock.json, Server/package.json, Server/service/jobQueue.js, Server/service/networkService.js, Server/service/statusService.js, Server/tests/services/networkService.test.js, Server/utils/messages.js
This PR adds support for a docker monitor.  This is a subtype of uptime monitor.
-[x] Update JobQueue, NetworkSerivce, and StatusService to support docker type monitors
Currently there is no need for a distinct docker type check as we are currently only interested in whether or not the container is running.  This is the same information that we have for a base http/ping type `Check`, so that type is used.  We can implement a distinct docker type check if we need more information later.
Docker monitors use a docker image ID in the `url` field of the monitor.
=> feat/be/docker monitors, references #1139

Client/src/Features/UptimeMonitors/uptimeMonitorsSlice.js, Client/src/Pages/Monitors/CreateMonitor/index.jsx, Client/src/Pages/Monitors/Home/MonitorTable/index.jsx, Server/db/mongo/modules/monitorModule.js, Server/service/networkService.js, Server/validation/joi.js
This PR implements the FE component of #1139, builds off #1150
=> Feat/fe/docker monitors, resolves #1139

Server/db/mongo/MongoDB.js, Server/db/mongo/modules/pageSpeedCheckModule.js, Server/tests/db/pageSpeedCheckModule.test.js
This PR adds tests for the `pageSpeedCheck` DB module
=> Remove unused DB method, add tests for pageSpeedCheckModule

Server/tests/utils/logger.test.js
This PR adds a missing test case to the logger test suite
=> Add missing logger test case

Server/package-lock.json, Server/package.json
This PR removes the sendgrid dependency from the backend.  Sendgrid was used to send emails in the past, we are using nodemailer now.
=> Remove sendgrid dependency from BE

Server/tests/db/monitorModule.test.js
This PR adds a missing test case for `getMonitorStatsById`.  A test case for docker type monitors was missing.
=> Add missing test case for docker monitor type

Client/src/Components/Inputs/Checkbox/index.jsx, Client/src/Components/Inputs/Field/index.jsx
Fixes some problem with colors on:
=> Hot fix/theme disabled

package-lock.json
Remove `/package-lock.json` that comes with pr-987. It not breaks anything because it's top level.
=> fix: Remove top level package-lock.json

Server/controllers/monitorController.js, Server/tests/controllers/monitorController.test.js
This PR rewrites the endpoint resolution functionality.  The original implementation was insufficient and only handle DNS resolution, which is only a subset of resolution we need to check.
=> fix: rewrite BE endpoint resolution method

Client/src/Pages/Infrastructure/CreateMonitor/index.jsx
=> 1181 remove upcoming features

Client/src/Pages/Incidents/IncidentTable/index.jsx
This PR changes the default `loading` state on the incident tage to `false`.  In the case when there are no monitors, the page returns without doing anything to the `loading` state, so the page is stuck in loading status.
This results in the wrong view presented when no monitors exist.
=> set initial loading state to false, resolves #1182

Server/service/statusService.js, Server/tests/services/statusService.test.js
This PR improves status string generation for monitor status chagnes.  Previously if a monitor went from an unknown state to a down state the logger would log "monitor went from down to down".
Now the logger will correctly log "monitor went from unknown to down"
=> Add better status string generation

Client/src/Components/Check/Check.jsx, Client/src/Components/Inputs/TextInput/index.jsx, Client/src/Pages/Auth/Register/StepOne/index.jsx, Client/src/Pages/Auth/Register/StepThree/index.jsx, Client/src/Pages/Auth/Register/StepTwo/index.jsx
This PR integrates `TextInput` into the register page
=> fix: fe/text input register

Client/src/Components/Inputs/TextInput/Adornments/index.jsx, Client/src/Pages/Auth/Login.jsx
This PR integrates `TextInput` into the login page
=> fix: fe/login text input

Client/src/Pages/Monitors/CreateMonitor/index.jsx
This PR integrates `TextInput` into the create monitors page.
=> fix: create monitor text field

Client/src/Pages/Infrastructure/CreateMonitor/index.jsx
This PR adds a link to the monitoring agent repository and an explanation that the agent must be running on the target server
=> feat: add link to monitoring agent

Client/package-lock.json, Client/package.json, Server/package-lock.json, Server/validation/joi.js
This PR adds the hardware type to BE validation for fetching monitors by team ID.
=> feat: be/hardware monitor team summary

Client/src/Components/Charts/BarChart/index.jsx, Client/src/Components/Label/index.jsx, Client/src/Utils/Theme/constants.js, Client/src/Utils/Theme/darkTheme.js, Client/src/Utils/Theme/globalTheme.js, Client/src/Utils/Theme/lightTheme.js
This PR implements some color fixes after refactoring theme
- Not sure if this is the correct approach, but the colors appear to be correct.
- Again I'm not sure if this is the correct approach, this will apply a color meant for borders to all disabled states?  
@marcelluscaio you know the most about the theme structure so please let me know if there is a better way to resovle these issues!
=> fix: adjusted theme settings for color fixes, references #1178

Client/src/Components/Sidebar/index.jsx, Client/src/Pages/PageSpeed/index.jsx
This PR removes the "Dashboards" top level menu item and moves the previous submenus Monitors, Pagespeed, and Infrastructure to the top level of the menu.
=> feat: fe sidebar restructure

Client/src/Pages/Infrastructure/CreateMonitor/index.jsx, Client/src/Pages/Monitors/CreateMonitor/index.jsx, Client/src/Pages/PageSpeed/CreatePageSpeed/index.jsx, Client/src/Utils/monitorUtils.js
This PR implements adding a name to a monitor when a URL is entered
Parsing a domain from a URL is non-trivial, so this is a pretty simple version.  It tries to figure out what the domain is, and if it can't, it just returns the original URL.
www.google.com -> Google
www.test.google.com -> www.test.google.com
123.123.123 -> 123.123.123
www.google -> Google
www.google. -> Google
.www.google.com -> Google
...google.com... -> Google
There are _many_ edge cases, so if anyone wants to spend time coming up with a better algorithm by all means, please do :joy:
=> feat: create monitor display name, resovles #992

Client/src/Pages/Auth/Login.jsx, Client/src/Utils/Theme/globalTheme.js
This PR replaces the regular button on the login page with a `LoadingButton` to indicate loading is in progress.
[Screencast from 2024-11-27 13-58-56.webm](https://github.com/user-attachments/assets/01cfcc9e-fa6b-433d-bdff-1136ebaae8b9)
=> fix: FE loading button on login page, resolves #1122

Client/src/Pages/Account/index.jsx, Docker/prod/nginx/conf.d/cerbot, Docker/prod/nginx/conf.d/default.conf, Docker/test/build_images.sh, Docker/test/client.Dockerfile, Docker/test/docker-compose.yaml, Docker/test/mongo/init/create_users.js, Docker/test/mongoDB.Dockerfile, Docker/test/nginx/conf.d/certbot, Docker/test/nginx/conf.d/default.conf, Docker/test/prod/build_images.sh, Docker/test/prod/client.Dockerfile, Docker/test/prod/docker-compose.yaml, Docker/test/prod/mongo/init/create_users.js, Docker/test/prod/mongoDB.Dockerfile, Docker/test/prod/nginx/conf.d/default.conf, Docker/test/prod/redis.Dockerfile, Docker/test/prod/server.Dockerfile, Docker/test/redis.Dockerfile, Docker/test/server.Dockerfile
This PR creates a test deployment config that will use ngixn and certbot
=> feat: test server deployment

Client/src/Pages/Account/index.jsx
This pull request resolves issue #1121 by adding visual cues to `Account` tabs. 
Styling improvements: 
Modified styles to add a border to the bottom of tabs when they are focused or hovered.
https://github.com/user-attachments/assets/796d9694-ca3f-4ee1-a0bd-87ffff742960
Issue: #1121
=> Feature - Added visual cues to Account tabs

Client/src/Components/HttpStatusLabel/index.jsx, Client/src/Pages/Monitors/Home/index.jsx
This PR fixes some undefined colors in the `HttpStatusLabel` component.  It also removes a few forgotton log statements
=> fix: undefined colors, removed log statements, resolves #1243

Client/src/Pages/Infrastructure/index.jsx
This PR fixes the issue of the page content width of the **Infrastructure Page**, the route is `/infrastructure`, wherein its page content width is wider than the other pages; resulting also in making the sidebar width smaller.
- Updated the **Infrastructure Page** to use `div` element instead of the `main` element as the main container for the page content
Closes #1241 
**Before:**
**After:**
N/A
=> fix: Infrastructure page content width

Client/src/Pages/Account/index.jsx, Client/src/Utils/Theme/constants.js, Client/src/Utils/Theme/globalTheme.js, Client/src/Utils/Theme/lightTheme.js
Fixes: https://github.com/bluewave-labs/checkmate/issues/1242
=> fix: fixing button color text on dark mode

Client/src/Utils/Theme/globalTheme.js
Solves https://github.com/bluewave-labs/checkmate/issues/1257
=> fix: disabled input

Docker/test/cerbot-compose.yaml, Server/db/mongo/modules/hardwareCheckModule.js, Server/tests/db/hardwareCheckModule.test.js
This PR updates tests for the hardware check module after changes were made to include uptime percentage.
=> fix: update tests for hardware check module

Client/src/Pages/Monitors/CreateMonitor/index.jsx
This PR resolves a bug wherein the http/https start adornment was shown on the monitor URL field even if a non http type monitor is selected
=> fix: remove start adornment from non-http type monitors

Client/src/Utils/Theme/globalTheme.js
We were getting error message because of kebab case in object. Changed for WebkitTextFillColor
=> fix error message

Client/src/Validation/validation.js
This PR fixes the issue of the error message under `Confirm new password` field in the Password Panel.
- Changed the error message from `empty -> This field can't be empty`
Fixes #1206 
**Before**
**After**
N/A
=> fix: Update error message in Password panel, confirm new password field

Client/src/Components/TabPanels/Account/TeamPanel.jsx
Fixed Issue  #1268
"Administrator" should be "Super admin"
Changed this typo in TeamPanel.jsx
=> fix : "Administrator" changed to "Super admin" in TeamPanel

Client/src/Components/TabPanels/Account/PasswordPanel.jsx, Client/src/Validation/error.js
This PR fixes the issue for the password validation under `Account > Password`
- Updated password validation logic
- Added `getTouchedFieldErrors()` util function for errors
Fixes #1274 
https://github.com/user-attachments/assets/d4d7334a-d439-4a50-b19e-1c4c4e8d98cd
N/A
=> fix: Password validation on account

Docker/prod/docker-compose.yaml
This PR updates the API base URL for the production server.  This is needed because of the recent DNS change
=> fix: Fix API url

Client/src/Components/Inputs/Select/index.jsx, Client/src/Pages/AdvancedSettings/index.jsx
This PR addresses the issue under #1289 
Changes done under this PR:
- Fixed the alignment issue with the "JWT TTL Units" dropdown
Before the fix:
After the fix:
=> fixed issue with the alignment in JWT section

Client/src/Pages/Infrastructure/CreateMonitor/index.jsx
This PR fixes the links in the Create Infrastructure Monitor Page
=> fix: links in create infra monitor page, resolves #1294

Client/src/Components/TabPanels/Account/PasswordPanel.jsx, Client/src/Components/TabPanels/Account/ProfilePanel.jsx, Client/src/Components/TabPanels/Account/TeamPanel.jsx
Added a constant spacing gap between labels and input in the following files: PasswordPanel.jsx , ProfilePanel.jsx ,TeamPanel.jsx
issue : #1720
- [ Yes] I have performed a self-review of my code.
- [ Yes] I have included the issue # in the PR.
- [ Yes] I have labelled the PR correctly.
- [ Yes] My PR is granular and targeted to one specific feature only.
=> Added a gap between label and inputs #1270

Client/src/Utils/Theme/globalTheme.js
This PR addresses issue #1275, where the "Current Password" field in the Password page displayed a white background when using the dark theme. The issue was identified as being linked to Chrome's autofill feature, which applies a default white background to input fields when auto filling saved credentials.
Changes: 
Just added a few lines of code under _globalTheme.js_:
Testing:
1. Reproduced the issue using saved passwords in Chrome.
2. Applied the fix and tested in multiple scenarios:
3. Dark theme with autofill.
4. Dark theme without autofill.
5. Light theme.
6. Incognito mode and cleared cache.
Attached before-and-after screenshots for reference.
Before:
After:
Let me know if there are any additional checks or refinements needed!
=> feat #1275: design corrected  : Current Password Field BG color

Client/src/Components/Sidebar/index.jsx
This PR resolves issue #1290 fixing the empty space caused by the height mismatch of the viewport and sidebar. Also fixes the overflowing content of the profile section at the bottom of the sidebar.
=> Fix Sidebar height to occupy viewport height

Client/src/Pages/Infrastructure/CreateMonitor/index.jsx, Client/src/Pages/Monitors/CreateMonitor/index.jsx
=> - Remove text from configuration

Client/src/Components/Label/index.jsx
=> - Change to grey  color for pending status

Client/src/Components/Inputs/Search/index.jsx
This PR fixes the issue for the search bar height
- Updated the padding of the _Search_ component
Fixes #1322 
**Before:**
**After:**
N/A
=> Fix: Adjust Search Bar height

Client/src/Pages/Infrastructure/index.jsx, Client/src/Pages/PageSpeed/index.jsx
This PR fixes the veritcal button spacing issue on the Infrasctructure page
=> Fix/fe/infra button vertical spacing, resolves #1332, resolves #1334

Client/src/Pages/Monitors/Home/CurrentMonitoring/index.jsx, Client/src/Pages/Monitors/Home/MonitorTable/index.jsx, Client/src/Pages/Monitors/Home/actionsMenu.jsx, Client/src/Pages/Monitors/Home/index.jsx
This PR resovles the monitor pause count not being updated when a monitor is paused.
The issue is a result of how network calls are being made.  The network call for aggregate monitor stats including pause count happens in the `Monitors` page, whereas the data for individual montiors is fetched in the Monitors Table.
This PR adds a trigger state to the aggergate stat fetching `useEffect` dependency array, and the trigger state is set when the pause button is pressed.  This will cause the aggregate data to be refetched and the pause count to be correctly updated.
=> fix: FE monitor pause count resolves #1325

Client/src/Pages/Infrastructure/index.jsx
This PR just restores a functions that was deleted and was left unused in the code
=> refactor: reverting unused function in infrastructure page

Server/controllers/monitorController.js, Server/db/mongo/MongoDB.js, Server/db/mongo/modules/hardwareCheckModule.js
HardwareChecks should be deleted when a monitor is deleted.
=> add deleteHardwareChecksByMonitorId

Client/src/Pages/Infrastructure/Details/index.jsx
Minor UI change(text update) from `Usage` -> `usage` in Memory and CPU category for maintaining wording consistency.
Fixes the Issue #1350
=> Changed text from "Usage" to "usage" in UI

Docker/dist/nginx/conf.d/default.conf, Docker/test/docker-compose.yaml, Docker/test/prod/docker-compose.yaml, Docker/test/prod/nginx/conf.d/default.conf, Server/openapi.json, guides/README.md, guides/developers-guide/general-project-structure.md, guides/users-guide/quickstart.md
I noticed that the [back end api documentation link](https://bluewavelabs.gitbook.io/checkmate/developers-guide/general-project-structure#back-end) is broken. I changed the demo server URL from `uptime-demo.bluewavelabs.ca` to `checkmate-demo.bluewavelabs.ca` across multiple files.
- nginx configs
- `UPTIME_APP_API_BASE_URL` values in docker compose files
- guides/
- openapi.json
=> fix: update demo server URLs to 'checkmate-demo.bluewavelabs.ca'

Client/src/Components/Inputs/Checkbox/index.jsx, Client/src/Pages/Infrastructure/CreateMonitor/CustomThreshold/index.jsx, Client/src/Pages/Infrastructure/CreateMonitor/index.jsx, Client/src/Validation/validation.js
This PR refactors the Create Infrastrucutre Monitor page to reduce complexity.
=> fix: fe/create infra refactor

Client/src/Pages/Uptime/Home/fallback.jsx
This PR fixes a link in the Uptime fallback component
=> fix: fallback link

renovate.json
Dependabot assigning `dependencies` label for issue/pr categorization and it makes easy to filtering the PRs. This feature is also available on Renovate according to it's [documentation](https://docs.renovatebot.com/configuration-options/#labels)
=> chore(renovate): Auto label assign on Renovate PRs

Client/src/Components/Sidebar/index.jsx
This PR addresses the logo navigation issue.
=> fix: logo navigation, resolves #1320

Client/src/Pages/PageSpeed/Configure/index.jsx, Client/src/Pages/Uptime/Configure/index.jsx
This PR adds a toast to be displayed on pause/resume of monitor
=> fix: add pause toast to PageSpeed and Uptime configure pages, resolves #1380

Server/controllers/authController.js
This PR resolves the issue where if you enter an incorrect password when tryring to update your password you are logged out.
The reason for this is that we have an axios interceptor that boots the user on any 401 responses, ie trying to access resources that they don't have access to.
This is a special case where we don't want the user booted, so an incorrect password on reset now returns 403 instead of 401 which doesn't trigger the interceptor.
=> fix: incorrect password on password change causes user to be logged out, resolves #1384

Client/src/Components/Avatar/index.jsx
Issue #1402
To use Checkmate blue color for avatar background color has been changed.
=> Changed the avatar color to checkmate blue color

Client/src/Routes/index.jsx
Incorrect login import updated
=> hotfix: login import

Client/src/Components/BasicTable/index.jsx, Client/src/Components/TabPanels/Account/TeamPanel.jsx
This PR adds an empty veiw Prop to the `BasicTable` component and displays the supplied string as a table row.
=> feat: fe/team empty view, resolves #1400

Client/src/Components/Inputs/Radio/index.jsx
Changed the visibility of the radio buttons and made it darker.
#1404
=> Add a new uptime monitor > Radio buttons: unselected radio buttons are hard to see #1404 #1412

Client/src/Components/ProtectedRoute/index.jsx
This PR fixes the prop type for the `ProtectedRoute` component
=> fix: protected route proptype

Client/src/Pages/Account/index.jsx
Added a fixed border of same height of the border that appears while hovering the tab. 
#1438 
https://github.com/user-attachments/assets/ae4acfa7-69f3-4259-b554-60e490a5e1cf
=> Tab bars are displayed upwards when hovered on them #1438

Server/eslint.config.js, Server/package-lock.json, Server/package.json
This pull request updates the development toolchain/toolset of the Server side of the Checkmate.
Install ESlint to the server side with `npm init @eslint/config@latest`
Update configuration according to docs, for working with js and mocha environments.
Add new `package.json` scripts to run with npm cli. 
- **npm run lint**
It checks for code lint rules in the code base.
- **npm run lint-fix**
It applies fixes for lint errors and warnings.
Add new `package.json` scripts to run with npm cli. 
- **npm run format**
It formats all the code base with a single command.
- **npm run format-check**
It checks for code style issues in the code base.
- `@eslint/js` = `^9.17.0`
- `eslint` = `^9.17.0`
- `eslint-plugin-mocha` = `^10.5.0`
- `globals` = `^15.14.0`
=> Update development toolchain of the `Server/`

Server/utils/messages.js
This PR removes a duplicate success message
=> fix: remove duplicate msg, resolves #1446

Server/db/mongo/modules/hardwareCheckModule.js
This PR fixes a concurrency issue where if a monitor is updated after it has been queried and a save is attempted.
=> fix: hardware-check concurrency issue

Docker/prod/server.Dockerfile, Server/package-lock.json, Server/package.json
This PR adds an environemntal var to the production Docker image to increase the available memory for the heap.  I investigated the possiblity of a memory leak but was unable to find anything significant.  It's possible the default heap size allocation is insufficient.
There is also an issue with the Bcrypt library, it is using outdated dependencies that warn of potential memory leaks.  I didn't observer any while monitoring the server, but it is possible this is causing the issue.  Hopefully the Bcrypt team will update their project soon.
=> fix: add env var to increase node heap size, bump server dependencies

Client/src/Pages/PageSpeed/Details/Charts/PieChart.jsx, Client/src/Pages/PageSpeed/Details/index.jsx, Client/src/Pages/PageSpeed/Details/styled.jsx, Client/src/Pages/Settings/index.jsx, Client/src/Utils/Theme/constants.js
- Fixed pie chart background color
- Added new color to theme 
- Changed success light to the new color (attention: this impacts current uses of success light in the project. In case of problem, change success light to success contrastText - which has the same value as success.light had before)
- Changed success contrast text for dark theme
- Fixed overflow on Metric box in pagespeed > details
Solves https://github.com/bluewave-labs/checkmate/issues/1331
=> fix: pie chart colors and Metrics box that was overflowing

Server/controllers/authController.js, Server/openapi.json, Server/templates/employeeActivation.mjml, Server/templates/noIncidentsThisWeek.mjml, Server/templates/passwordReset.mjml, Server/templates/serverIsDown.mjml, Server/templates/serverIsUp.mjml, Server/templates/welcomeEmail.mjml, Server/tests/controllers/authController.test.js
There are also old naming under the `Client/` directory. If you are thinking changing all `BlueWave Uptime` strings to `Checkmate` in this PR please let me know.
I'm not thinking about updating docs, guides for now.
=> Fix: Old name reference on the Server Side

Client/src/Components/BasicTable/index.jsx, Client/src/Pages/Uptime/Home/UptimeTable/index.jsx
I decided to move away from changing background color and try a filter approach, that is applied to the whole row, which will help  keep consistency (everything changes at once)
Solves: https://github.com/bluewave-labs/checkmate/issues/1323
=> fix: row background color on hover

Client/src/Components/Sidebar/index.jsx, Client/src/Pages/Uptime/Home/UptimeTable/index.jsx
Addresses 4 of the 5 points in this issue https://github.com/bluewave-labs/checkmate/issues/1399
=> feat: adjustments to sidebar

Client/src/Pages/Uptime/Home/index.jsx
This PR adds a `!loading` flag to the conditional rendering of the fallback component.
This component should not display while the page is loading, it should only display when it is certain that there are no montiors.
=> fix: add additional not loading flag to fallback conditional rendering, resolves #1426

Client/src/Utils/Theme/constants.js, Client/src/Utils/Theme/darkTheme.js, Client/src/Utils/Theme/globalTheme.js, Client/src/Utils/Theme/lightTheme.js
Added new semantic color (neuter) and added to MUI settings
Fixed Buttons contrast
=> Fix: group buttons contrast text

Docker/dev/docker-compose.yaml, Docker/dist/docker-compose.yaml, Docker/prod/docker-compose.yaml, Docker/test/docker-compose.yaml
This PR adds the `restart:always` flag to the docker-compose files.
=> fix: always restart docker images

Docker/test/docker-compose.yaml
This PR updates the test config's API base url
=> fix test config docker-compose URL

Server/index.js
This PR moves middleware that uses `JobQueue` to after `JobQueue` initialization
=> hotfix: move middleware to after JobQueue initialization

Client/src/Pages/Uptime/Details/index.jsx
Moved certificate expiry to a card.
#1327
=> Move certificate expiry to a card #1327

Client/src/Pages/Uptime/Details/index.jsx
This PR fixes incorrect usage of a date format for the SSL certificate expiry format string.
It also removes unused imports
=> hotfix: fix certificate format

Server/service/jobQueue.js
This PR converts some blocking calls into non-blocking calls.
Adding jobs to the Queue and scaling workers was causing the thread to be blocked, those processes can be handled asynchronously.
=> hotfix: made adding jobs and scaling workers non-blocking

Client/src/Components/Sidebar/index.jsx
Changed the navbar path map
#1485 
https://github.com/user-attachments/assets/1224e37d-5e9a-4c3f-8374-3c19c4040909
=> Clicking on settings shouldn't open the "Other" drawer, resolves #1485

Server/db/models/Monitor.js, Server/index.js, Server/service/networkService.js, Server/service/statusService.js, Server/utils/messages.js, Server/validation/joi.js
This PR implements the backend portion of port monitoring
=> feat: be/tcp port monitoring, references #1476

Client/src/Features/UptimeMonitors/uptimeMonitorsSlice.js, Client/src/Pages/Uptime/CreateUptime/index.jsx, Client/src/Pages/Uptime/Details/index.jsx, Client/src/Pages/Uptime/Home/UptimeTable/index.jsx, Client/src/Validation/validation.js, Server/db/mongo/modules/monitorModule.js, Server/validation/joi.js
This PR is the FE half of port monitoring
=> feat: fe/tcp port monitoring, resolves #1476

Client/src/Utils/Theme/constants.js
Changed the colour property of hover
#1335 
https://github.com/user-attachments/assets/dd18a367-c725-4014-bb1a-06d51014bf00
=> Red button mouse hover status has wrong color #1335

Server/db/models/Check.js, Server/db/models/HardwareCheck.js, Server/db/mongo/MongoDB.js, Server/db/mongo/modules/monitorModule.js
This PR adds indices to some models to improve query performance.  Some queries, especially check queries, have a lot of data and can benefit from DB indices.
=> fix: be/db indices

Server/db/models/DistributedUptimeCheck.js, Server/db/models/Monitor.js
This PR updates the Monitor model to allow for a distributed uptime monitor type and adds a distributed uptime check model
=> feat: be/distributed uptime model

Server/db/mongo/modules/hardwareCheckModule.js, Server/index.js, Server/package-lock.json, Server/package.json, Server/service/jobQueue.js
This PR improves the `JobQueue` to better handle higher job loads.  It implements separate queues for each type of monitor (uptime, pagespeed, infrastructure). 
Error handling is more robust to help stop the queue from becoming blocked:
It also flushes the Redis DB in the event that the server cannot shut down gracefully.  This should help prevent orphaned jobs which seem to block the queue
=> fix: be/improved jobqueue

Client/src/Utils/NetworkService.js
This hotfix adds missing auth headers to a request
=> add missing auth headers to hardware-details request

Client/src/Components/TabPanels/Account/PasswordPanel.jsx
- Left aligning password component to match the profile page alignment.
- Edited `Client/src/Components/TabPanels/PasswordPanel.jsx`, removed marginInline and changed alignItems to flex-start
Fixes #1508 
Screenshots:
Light Mode:
Dark Mode:
=> Left align Profile > Password components

Client/src/Validation/validation.js
This PR resovles a backtracking isue with a regex used to verify URLs on the client side.
=> hotfix: fe/monitor validation, resolves #1518

Docker/dev/docker-compose.yaml, Docker/dist/docker-compose.yaml, Docker/prod/docker-compose.yaml, Docker/test/docker-compose.yaml
This PR adds a health check to the docker-compose files for the Redis image.  This should improve stability as the server won't try to connect before Redis responds to the ping.
=> feat: devops/add healthcheck to redis image

Server/service/jobQueue.js
This PR adds more logging to the JobQueue class to help diagnose stalled queue issues
=> hotfic: add more logging to jobqueue

Client/src/Components/Charts/MonitorDetailsAreaChart/index.jsx, Client/src/Components/Charts/Utils/chartUtilFunctions.js, Client/src/Components/Charts/Utils/chartUtils.jsx, Client/src/Pages/Infrastructure/Details/index.jsx, Client/src/Pages/Uptime/Details/index.jsx
This PR fixes the x-axis on the bar and area charts so that the dates on the x-axis match the grouping periods for their respective data windows:
day - hour
week - hour
month - day
[Screencast from 2025-01-02 14-25-37.webm](https://github.com/user-attachments/assets/6d022824-8861-48c1-aefa-721bf2069935)
=> fix: fe/charts date display

Client/src/Pages/Uptime/CreateUptime/index.jsx, Client/src/Pages/Uptime/Home/index.jsx, Server/controllers/monitorController.js, Server/db/mongo/modules/monitorModule.js, Server/routes/monitorRoute.js, Server/service/jobQueue.js, Server/service/settingsService.js, Server/validation/joi.js
This PR simplifies the monitor summary endpoint and redux slice.
Previously a list of monitors was stored in the redux state, this is no longer needed, so the monitors have been removed from the query.  Now only a summary is returned
=> remove monitors from summary, unused

Server/db/mongo/modules/checkModule.js
Query updated for Incidents page to make the filters working. As per the BaseCheckSchema status can have true and false values in it. We have 3 filters in this page All, Down and Cannot Resolve in UI , on schema side we can true for up, false for down. So now when we click Down we will get status which are set to false and clicking on Cannot resolve will bring records which have status true.
#1112
=> Query updated for Incidents page filter

Client/src/Features/PageSpeedMonitor/pageSpeedMonitorSlice.js, Client/src/Features/UptimeMonitors/uptimeMonitorsSlice.js, Client/src/Pages/Infrastructure/index.jsx, Client/src/Pages/PageSpeed/card.jsx, Client/src/Pages/PageSpeed/index.jsx, Client/src/Pages/Uptime/Home/UptimeDataTable/index.jsx, Client/src/Pages/Uptime/Home/actionsMenu.jsx, Client/src/Pages/Uptime/Home/index.jsx, Client/src/Utils/NetworkService.js, Server/controllers/monitorController.js, Server/db/mongo/modules/monitorModule.js, Server/routes/monitorRoute.js, Server/validation/joi.js
This PR unifies two separate queries that were made in order to fetch monitors.  Previously, one query was made for a summary of monitors, one query made for a list of monitors with checks.  Now one query is made using the aggregate pipeline and facets in order to get all the data in one go. 
In order to make use of these queries some changes were requried on the FE.  There is no need to store these monitors in the redux state any longer, so fetching has been moved to the component.  Unnecessary redux thunks are removed and loading managed locally.
=> feat: be/unified uptime query

Client/src/Pages/Uptime/Home/index.jsx, Server/db/mongo/modules/monitorModule.js
This PR moves the filtering portion of the match stage to the monitors facet instead of matching before the facets.
Filtering by name should only be done _after_ building summary data.
=> hotfix: move filtering to the monitors facet

Client/src/Components/Inputs/Search/index.jsx, Client/src/Pages/Uptime/Home/UptimeDataTable/index.jsx, Client/src/Pages/Uptime/Home/index.jsx
This PR addresses unnecessary rerenders of the UptimeDataTable due to the autocomplete feature.
=> fix: fix unnecessary rerenders

Client/src/Pages/Incidents/index.jsx, Server/controllers/monitorController.js, Server/db/mongo/modules/monitorModule.js
This PR resolves #1538.  The aggregate pipeline doesn't deal with negative values for `limit` gracefully so `null` is used instead.
=> hotfix: fe/be/incidents page

Client/src/Utils/NetworkService.js
Created toast notifications that will alert the admin whenever there is a server issue and would inform admin too when there would be proper functioning of the server.
1482: https://github.com/bluewave-labs/checkmate/issues/assigned/jasneetsingh6114
- [ Done] I deployed the application locally.
- [ Done] I have performed a self-review and testing of my code.
- [ Done] I have included the issue # in the PR.
- [Done ] I have labelled the PR correctly.
- [ Done] The issue I am working on is assigned to me.
- [ I didn't hard-coded any values] I didn't use any hardcoded values (otherwise it will not scale, and will make it difficult to maintain consistency across the application).
- [Done ] I made sure font sizes, color choices etc are all referenced from the theme.
- [Done ] My PR is granular …
=> Inform Admin incase of server issue.

Server/service/jobQueue.js
BullMQ recently depcrecated their [Repeatable API](https://docs.bullmq.io/guide/jobs/repeatable) in favour of their [Job Scheudler API](https://docs.bullmq.io/guide/job-schedulers)
This PR migrates to the new API.  This is timely as there were some issues with repeatable getting stuck anyways.
=> fix: use jobScheduler instead of deprecatred repeatable

Server/db/mongo/modules/monitorModule.js
This PR adds a default sort order for monitors of [NAME, asc] if the user hasn't chosen to sort by name or status, ie when they first visit the page.
=> hotfix: add a default sort order if a field to sort by is not specified

Client/src/Pages/Uptime/Home/index.jsx
The logic for `hasMonitors` was incorrect, looks like probably a copy/paste error occurred at some point.
=> fix: hasMonitors logic

Server/templates/serverIsDown.mjml
Was static google.com is now the monitor name in the header
The mjml/email `serverIsDown` always showed _google.com_ is down in any monitor.
Now it shows the actual name of the monitor that went down.
=> Fix server is down mjml to show monitor name

Server/controllers/authController.js, Server/controllers/checkController.js, Server/controllers/controllerUtils.js, Server/controllers/inviteController.js, Server/controllers/maintenanceWindowController.js, Server/controllers/monitorController.js, Server/controllers/queueController.js, Server/controllers/settingsController.js, Server/controllers/statusPageController.js, Server/index.js, Server/middleware/handleErrors.js, Server/middleware/responseHandler.js, Server/utils/messages.js
This PR adds a resonse handling middleware to enforce consistent network responses from the Server.  This will help with future collaboration as there is a clearly defined method of creating and returning responses.
Consistency will be key in creating a predictable API, which will lead to better handling of resonses on the front end.
=> feat: be/consistent response middleare

Client/src/Validation/validation.js
This hotfix removes a local IP address exclusion from the monitor validation regex
=> fix: remove local IP address exclusion from moniotr validation regex

Server/service/jobQueue.js
This PR adds missing port types to the queue mapping
=> hotfix: add port type monitors to queue mapping

Client/src/Pages/Uptime/CreateUptime/index.jsx
=> Move "Checks to perform" to the top of "General settings"

.npmrc, package-lock.json
I added top level `.npmrc` file for configuring npm package manager on the runtime. The change disables the generation of `package-lock.json` files by setting `package-lock=false`. I hope we won't see top level `package-lock` from now on. #1162 
The `npm install` command used in the wrong directory causes this `package-lock.json` to be created automatically.
---
=> Remove package-lock.json and add '.npmrc' to disable lockfile generation

Server/db/mongo/modules/checkModule.js, Server/db/mongo/modules/monitorModule.js, Server/db/mongo/modules/monitorModuleQueries.js
This PR updates some DB queries to return consistent results, 0 instead of null for empty data
=> update queries to return consistent values

Client/src/Pages/Uptime/Details/Hooks/useCertificateFetch.jsx, Client/src/Pages/Uptime/Details/Hooks/useChecksFetch.jsx, Client/src/Pages/Uptime/Details/Hooks/useMonitorFetch.jsx, Client/src/Pages/Uptime/Details/index.jsx
This PR adds a network error empty veiw to `Uptime Details` that matches all other pages.
=> fix: add a network error view for Uptime details

Client/src/Pages/StatusPage/Status/Components/ControlsHeader/index.jsx, Client/src/Pages/StatusPage/Status/Components/StatusBar/index.jsx
This PR hides the delete and configure buttons on the public status page
=> fix: don't render control buttons for public status page

Client/src/Pages/Account/index.jsx, Client/src/Utils/Theme/globalTheme.js
This PR fixes tab styles.  Previously tab styles were declared inline and only applied to the particular component.
This PR moves the tab styles to the Theme so they apply to all tabs
=> fix: move tab styles to theme so they apply globally

Client/src/Components/Dialog/index.jsx, Client/src/Pages/Account/index.jsx, Client/src/Pages/StatusPage/Status/Components/ControlsHeader/index.jsx, Client/src/Pages/StatusPage/Status/index.jsx, Client/src/Utils/Theme/globalTheme.js
This PR adds a delete confirmation modal to the Status Page
=> fix: fe/status page delete modal

Docker/test/docker-compose.yaml
This PR updates the docker-compose file for the test server.  It starts MongoDB in replicaset mode
=> update docker compose for replica set

.gitignore, Client/src/Pages/DistributedUptime/Details/Components/DistributedUptimeMap/DistributedUptimeMapStyle.json, Client/src/Pages/DistributedUptime/Details/Components/DistributedUptimeMap/buildStyle.js, Client/src/Pages/DistributedUptime/Details/Components/DistributedUptimeMap/index.jsx, Client/src/Utils/Theme/constants.js
This PR updates the DU map so that it respects the client theme
=> feat: fe/du map theme

Client/src/Components/ActionsMenu/index.jsx, Client/src/Pages/Uptime/Monitors/Components/UptimeDataTable/index.jsx, Client/src/Pages/Uptime/Monitors/index.jsx
This PR removes remnants of an old loading state which was causing the "Create" button to become stuck in a loading state.
=> fix: remove old loading state

Client/package-lock.json, Client/package.json, Client/src/Components/LanguageSelector.jsx, Client/src/Pages/DistributedUptime/Details/Components/DeviceTicker/index.jsx, Client/src/Utils/i18n.js
This PR removes react-world-flags as we already have a flag libary, [Flag icons](https://flagicons.lipis.dev/).  A second flag library is unnecessary.
=> fix: remove react-world-flags, only one flag library needed

Client/src/Pages/StatusPage/Status/Components/ControlsHeader/index.jsx
This PR reverts a mistaken change to the Status page configure button link target
=> hotfix: stauts page config link

Client/src/Components/Sidebar/index.jsx
- Fixed visibility issue with sidemenu divider in dark mode by adjusting its color to use proper values
- Added scrollable functionality to sidemenu to prevent profile section from being pushed out of view when dropdowns are expanded
- Menu items now scroll independently while keeping the profile section fixed at the bottom
#1646
=> Fix: Sidemenu UI Overflows

Client/src/Features/UptimeMonitors/uptimeMonitorsSlice.js, Client/src/Pages/DistributedUptime/Create/Hooks/useCreateDistributedUptimeMonitor.jsx, Client/src/Pages/DistributedUptime/Create/Hooks/useMonitorFetch.jsx, Client/src/Pages/DistributedUptime/Create/index.jsx, Client/src/Pages/DistributedUptime/Details/Components/ControlsHeader/index.jsx, Client/src/Pages/DistributedUptime/Details/Hooks/useDeleteMonitor.jsx, Client/src/Pages/DistributedUptime/Details/index.jsx, Client/src/Pages/DistributedUptime/Monitors/Components/MonitorTable/index.jsx, Client/src/Pages/DistributedUptime/Monitors/index.jsx, Client/src/Pages/DistributedUptimeStatus/Create/index.jsx, Client/src/Pages/StatusPage/Create/index.jsx, Client/src/Pages/Uptime/Monitors/Components/UptimeDataTable/index.jsx, Client/src/Routes/index.jsx, Client/src/Utils/NetworkService.js, Server/controllers/monitorController.js, Server/db/mongo/modules/distributedCheckModule.js, Server/db/mongo/modules/monitorModule.js, Server/db/mongo/modules/statusPageModule.js
This PR implements configuration page for Distributed Uptime Monitors.  It also deals with deleting DU monitors and adds some helper methods for deleting asscociated records.
=> feat: fe/config du monitor

Client/src/Pages/Uptime/Details/Components/ChartBoxes/index.jsx, Server/db/mongo/modules/monitorModule.js
This PR fixes an issue where uptime percentage used the aggregate total number of checks for a monitor to calculate uptime percentage for a fixed period, which is incorrect.
Uptime percentage should be calculated by dividing the total number of up checks in a group by the total number of checks in the group.
=> fix: correctly calculate grouped uptime percentage, resolves #1684

Client/src/Components/Sidebar/index.jsx
- Fixed visibility issue with sidemenu divider in dark mode by adjusting its color to use proper values
- Added scrollable functionality to sidemenu to prevent profile section from being pushed out of view when dropdowns are expanded
- Menu items now scroll independently while keeping the profile section fixed at the bottom
#1646
=> Fix: Sidemenu UI Overflow

Client/src/Components/TabPanels/Account/PasswordPanel.jsx, Client/src/Components/TabPanels/Account/ProfilePanel.jsx, Client/src/Components/TabPanels/Account/TeamPanel.jsx, Client/src/Pages/Auth/ForgotPassword.jsx, Client/src/Pages/Auth/Login/Components/PasswordStep.jsx, Client/src/Pages/Auth/SetNewPassword.jsx, Client/src/Pages/DistributedUptime/Create/index.jsx, Client/src/Pages/Infrastructure/Create/index.jsx, Client/src/Pages/Maintenance/CreateMaintenance/index.jsx, Client/src/Pages/PageSpeed/Configure/index.jsx, Client/src/Pages/PageSpeed/Create/index.jsx, Client/src/Pages/Settings/index.jsx, Client/src/Pages/Uptime/Configure/index.jsx, Client/src/Pages/Uptime/Create/index.jsx, Client/src/Utils/Theme/globalTheme.js
This PR replaces `LoadingButton` with `Button` as `LoadingButton` [is now deprecated](https://mui.com/material-ui/migration/upgrade-to-v6/#button-with-loading-state) and its functionality rolled in to button.
@marcelluscaio if you could check out the theme and make sure I haven't broken anything that would be great.
=> fix: fe/loading buttons

Client/src/Pages/DistributedUptime/Details/index.jsx, Server/.gitignore, Server/service/networkService.js
This PR fixes some minor issues with Distributed uptime
=> fix: fe/be/du details

Server/index.js, Server/package-lock.json, Server/package.json, Server/service/networkService.js
This PR removes ngrok from the backend.
Ngrok was used to create a tunnel in order to receive callbacks from UpRock.
Creating a tunnel is now up to the developer, recommend using [zrok.io](https://zrok.io/).
Callback url must be specified in server .env file in order to receive callbacks:
`CALLBACK_URL="https://callback.share.zrok.io"`
=> fix: remove ngrok

src/Pages/Maintenance/index.jsx
Moved the fallback component outside the wrapper and got rid of the unnecessary box container to fix the layout issue
#1772 
Before: 
After:
=> Fix Maintenance page layout issue

src/Pages/Maintenance/CreateMaintenance/index.jsx
- Previously, the function expected selected monitors in the second argument, but the Search component only passes one argument.
- Now, the function correctly handles the selection by accepting only one parameter, ensuring the form updates as expected.
#1792
=> Fix create maintenance window issue

src/Pages/StatusPage/Status/Components/ControlsHeader/index.jsx
This PR adds a fixed height of 50px to the DePIN logo
=> fix: add fixed max logo height to DePIN status page

src/Pages/Infrastructure/Monitors/Components/MonitorsTable/index.jsx
This PR fixes a reference in the Infra monitors page:
`_id` -> `id`
for correct ID access
=> fix: infra monitor id

src/Pages/Uptime/Create/index.jsx
=> Made notification integrations button.

src/Pages/Maintenance/index.jsx
Changes were lost during prism sync
=> fix: re-commit changes for maintenance page

src/Pages/DistributedUptime/Create/index.jsx, src/Pages/DistributedUptimeStatus/Create/index.jsx
This PR fixes the issue presented in #1829
A variable was not updated after switching to a different hook.
Breadcrumbs are also updated to reflect proper location.
=> fix: breadcrumbs, resolves #1829

src/Components/Charts/ChartBox/EmptyView.jsx, src/Components/Charts/ChartBox/index.jsx, src/Pages/Uptime/Details/Components/ChartBoxes/index.jsx
This update modifies the incident display logic in the UI. It now conditionally renders the following:
- For existing incidents: The original layout is displayed with the count of total checks and the timestamp of the hovered incident.
- For "No incidents" scenario: A centered message saying "Great. No incidents, yet!" is shown.
[Have tested on Safari, Chrome & Firefox]
#1757
=> Fix: No Incidents Message

src/Components/Table/index.jsx, src/Pages/StatusPage/StatusPages/Components/StatusPagesTable/index.jsx
This PR adds a configurable `onClick` listener and styling for specifc cells in the `DataTable` component.
It adds an `onClick` listener to the status page table that opens the public status page if it is published.
=> feat: status table onclick

src/Features/UI/uiSlice.js, src/Pages/DistributedUptimeStatus/Status/index.jsx, src/Pages/StatusPage/Status/Components/ControlsHeader/index.jsx, src/Utils/Theme/constants.js
This PR adds a theme swticher to the DePIN public status page
=> feat: DePIN status page theme

src/Components/Alert/index.jsx, src/Pages/Account/index.jsx, src/Pages/StatusPage/Create/Components/Tabs/ConfigStack.jsx, src/Pages/StatusPage/Create/Components/Tabs/Content.jsx, src/Pages/StatusPage/Create/Components/Tabs/SectionStack.jsx, src/Utils/Theme/constants.js
1. Removed the common code and added a new component in order to reuse it in future.
2. Also removed the _sx={{ margin: theme.spacing(6) }}_ which was the causing the issues in the UI.
Briefly describe the changes you made and their purpose.
-> The alignment of divider line for the left and right box in the contents tab in status page.
-> Made changes in order to avoid any repeated code in the main code file. Ideally, even each section should be in different file but that will be abundance of files and we don’t need to increase it now. But atleast the developer should not worry about title and description component.
Small UI fixes #1848
=> FIX-1848 UI design changes

src/Pages/Settings/index.jsx
This PR groups DePIN settings items together on the settings page
=> group depin settings items

src/Pages/StatusPage/Create/Components/Tabs/Settings.jsx, src/Validation/validation.js
This PR adds further validation to the `url` field in Create Status Page to disallow reserved characters that can break routing.
=> fix: disallow reserved chars from status page valiation, resolves #1826

src/Components/Charts/Utils/chartUtilFunctions.js, src/Components/MonitorTimeFrameHeader/index.jsx, src/Pages/DistributedUptime/Details/Components/DeviceTicker/index.jsx, src/Pages/DistributedUptime/Details/Hooks/useSubscribeToDetails.jsx, src/Pages/DistributedUptime/Details/index.jsx, src/Pages/DistributedUptimeStatus/Status/index.jsx, src/Pages/Infrastructure/Details/Hooks/useHardwareMonitorsFetch.jsx, src/Pages/Infrastructure/Details/index.jsx, src/Pages/Uptime/Details/index.jsx
This PR adds a "recent" timeframe option to all of the Monitor details pages.  This will be the default detail view and groups checks by minutes.
=> feat: recent checks query

src/Components/Label/index.jsx, src/Pages/StatusPage/StatusPages/Components/StatusPagesTable/index.jsx
Replaced <ColoredLabel> component from "Status pages" with <StatusLabel> component as it was not being used anywhere else besides there.
https://github.com/bluewave-labs/Checkmate/issues/1892
=> fix: add <StatusLabel> on "status pages" table

.github/scripts/download-translations.js, .github/workflows/README.md, .github/workflows/poeditor-sync.yml
This GitHub Actions workflow automatically downloads translation files from POEditor and integrates them into the project.
The workflow can be triggered in two ways:
1. **Manual Trigger**: You can manually run the "POEditor Translation Synchronization" workflow from the "Actions" tab in the GitHub interface.
2. **Automatic Trigger**: The workflow runs automatically every day at midnight (UTC).
For this workflow to function, you need to define the following secrets in your GitHub repository:
1. `POEDITOR_API_TOKEN`: Your POEditor API token
2. `POEDITOR_PROJECT_ID`: Your POEditor project ID
You can add these secrets in the "Settings > Secrets and variables > Actions" section of your GitHub repository.
When running the workflow manually, you can specify which languages to download. Languages …
=> feat: Sync strings from poeditor with github workflow

src/Pages/Uptime/Details/Hooks/useChecksFetch.jsx, src/Pages/Uptime/Details/index.jsx
This PR addresses the issue of cases where the type parameter is not sent from the frontend. Currently, when type is not provided, it shows as undefined in the API, which can cause issues in processing.
=> Fix: Uptime UseChecks Hook

src/Pages/Uptime/Details/Hooks/useChecksFetch.jsx
This PR replaces throwing an error with `console.warn`
=> hotfix:replace throwing error with console.warn

src/Components/WalletProvider/index.css, src/Components/WalletProvider/index.jsx, src/Pages/Settings/index.jsx
Enhanced wallet button layout for better responsiveness and alignment.
Mention the issue number(s) this PR addresses #1794
=> Enhance wallet button layout for better responsiveness and alignment.

src/Pages/StatusPage/StatusPages/Components/StatusPagesTable/index.jsx
Changed     navigate(url) --> window.open(url, "_blank", "noopener,noreferrer") at line number 28.
_blank: Opens in a new tab.
"noopener,noreferrer": Security best practice to prevent access to the parent page.
Reason to change was that public url link should not have any option of redirecting into other pages of the application.
https://github.com/user-attachments/assets/1718a875-056c-41a0-997e-5fc362124182
---
- [ x ] I deployed the application locally.
- [ x ] I have performed a self-review and testing of my code.
- [ x ] I have included the issue # in the PR.
- [ x ] I have labelled the PR correctly.
- [ x ] The issue I am working on is assigned to me.
- [ x ] I didn't use any hardcoded values (otherwise it will not scale, and will make it difficult to maintain consistency across the …
=> Fix Open public url in new Tab(#1864)

src/Components/Table/TablePagination/index.jsx
Remove the page table navigation if the num of rows are less than specified. For ex, the status has only 7 and I say it to show only 10 then the left and right table nav should ideally be absent.
#1848 
- [] I have added i18n support to visible strings (instead of `<div>Add</div>`, use): 
```Javascript
```
https://github.com/user-attachments/assets/08dfc6fb-1078-429a-a7e6-7c34e9e680e6
=> FIX-1848 pagination changes.

src/Components/Charts/BarChart/index.jsx, src/Hooks/useFetchMonitorsWithChecks.js, src/Hooks/useFetchMonitorsWithSummary.js, src/Pages/Uptime/Monitors/index.jsx, src/Utils/NetworkService.js
This PR adds two new top level hooks:
1.  Hook for fetching list of monitors with summary.  This is useful for showing a summary of all monitors as well as providing a full list for searching through
2.  Hook for fetching a list of monitors with checks
Previously these two operations were combined in one hook, so the entire page would need to re-render when either set of data changes.
Now we can rerender only the necessary components.
=> fix: uptime refactor

src/Pages/Maintenance/CreateMaintenance/index.jsx
The colour (text) of disabled dates is dark in colour when the theme is dark.
#1935 
```Javascript
```
Before:
After:
=> Fixed calendar disabled date colour

src/Components/Dialog/index.jsx
The cancel option on multiple popups are like link instead of buttons, need to be a like button for better UI. I have made is like a button with gray bg.
#1936 
```Javascript
```
Before:
After:
https://github.com/user-attachments/assets/0959bb86-6a9a-4404-afda-e926a904d08a
=> Fix 1936 dark bg

src/Components/MonitorStatusHeader/index.jsx, src/Components/MonitorTimeFrameHeader/index.jsx, src/Hooks/useFetchUptimeMonitorDetails.js, src/Pages/StatusPage/StatusPages/Components/StatusPagesTable/index.jsx, src/Pages/Uptime/Details/Components/ChartBoxes/index.jsx, src/Pages/Uptime/Details/Components/Charts/DownBarChart.jsx, src/Pages/Uptime/Details/Components/Charts/ResponseTimeChart.jsx, src/Pages/Uptime/Details/Components/Charts/UpBarChart.jsx, src/Pages/Uptime/Details/Components/ResponseTable/index.jsx, src/Pages/Uptime/Details/Components/UptimeStatusBoxes/index.jsx, src/Pages/Uptime/Details/index.jsx, src/Utils/timeUtils.js
This PR updates the Uptime Details page to make use of improved queries on the BE.
1.  Use `MonitorStats` object for running stats
2. Change shouldRender -> isLoading, more symantically correct
3. Add missing proptypes
=> fix: update details page to use new queries

src/Features/Settings/settingsSlice.js
The set base url was causing a problem in settings page due to which it was sending the api to client url instead of base url which set in env or in network service
No issue as this is a quick fix for now
```Javascript
```
Before:
After:
=> Quick fix for settings save page api call

src/Components/Table/TablePagination/Actions/index.jsx
This PR address the issue of gap between the action buttons of Table Pagination Component.
```Javascript
```
=> Fix: Table Pagination Action Button Gap

src/Hooks/useSubscribeToDepinDetails.js, src/Utils/NetworkService.js
Status pages need a separate unsecure route
=> fix: add separate URL for public status pages

src/Pages/Account/index.jsx, src/Utils/Theme/globalTheme.js
- Set tab height to 34 px
- Changed tab background to match other similar components
- Removed hover background color
```Javascript
```
Before:
After:
Recording:
https://github.com/user-attachments/assets/7cbc0505-f7e9-41b8-a866-06bb7b58eada
=> Change Accounts tab styling

src/Pages/PageSpeed/Details/Components/PerformanceReport/index.jsx
Update text color in performance report to use `contrastTextTertiary`
```Javascript
```
Before:
After:
=> Fix text color in pagespeed monitor

src/Components/Sidebar/index.css, src/Components/Sidebar/index.jsx
- Fixed the issue where sidebar icons appeared before the sidebar finished expanding.
- Introduced a delayed `.sidebar-ready` class that's added only after the sidebar finishes expanding.
- Used this class to control the visibility of icons using CSS transition.
Fixes #1987 
```Javascript
```
Before:
https://github.com/user-attachments/assets/cd40aedd-60c6-42e8-9188-0a68785cbe39
After:
https://github.com/user-attachments/assets/fbb5427b-2c64-438b-941c-e5b5f7256b68
=> Fix sidebar menu icons appearing before full expansion

src/Components/Sidebar/index.css, src/Components/Sidebar/index.jsx
Fixed the icons visibility issue when toggling between themes
- We were using a CSS class `.sidebar-ready` that gets added after a delay (using setTimeout) to show the icons.
- But when the theme was toggled, the sidebar re-rendered and temporarily lost the .sidebar-ready class.
- Added a `sidebarReady` state to track readiness properly, independent of re-renders.
- Removed direct DOM manipulation (classList.add/remove) and instead used `sidebarReady` state to add the class through className.
```Javascript
```
Before:
https://github.com/user-attachments/assets/98483bf9-2d0e-4071-b995-182f4e4df9c9
After:
https://github.com/user-attachments/assets/60e81309-5b87-47a4-9dfb-b8b0f9c519d3
=> Fix sidebar icons visibility when toggling

src/Pages/StatusPage/Create/index.jsx, src/Pages/StatusPage/Status/index.jsx, src/locales/gb.json
Added breadcrumbs to status pages
#2057 
```Javascript
```
=> Status Pages breadcrumbs

server/validation/joi.js
This PR modifies the `ignoreTlsErrors` validation to provide a default `false` value
=> hotfix: validation

docker/dev/docker-compose.yaml, docker/dist/docker-compose.yaml, docker/prod/docker-compose.yaml
There is no need to expose redis and mongo ports in docker compose
=> fix: don't expose redis and mongo ports

client/src/Pages/Settings/index.jsx, client/src/Validation/validation.js
This PR is a hotfix for the incorrect implementation of showURL on the settings page.
The showURL setting was not properly loaded and validated, and had no error state.
This PR temporarily removes the showURL var from validation and does not submit to backend.
=> remove showURL from validation

client/src/Components/I18nLoader/index.jsx, client/src/Components/Inputs/Select/index.jsx, client/src/Components/LanguageSelector.jsx, client/src/Features/Settings/settingsSlice.js, client/src/Features/UI/uiSlice.js, client/src/Pages/Settings/SettingsURL.jsx, client/src/Pages/Settings/index.jsx, client/src/Pages/Uptime/Monitors/Components/StatusBoxes/index.jsx, client/src/Pages/Uptime/Monitors/Components/StatusBoxes/statusBox.jsx, client/src/Utils/NetworkService.js, client/src/Utils/i18n.js, client/src/main.jsx
This PR implements several fixes related to i18n
=> fix: refactor i18n, resolves #2374

server/controllers/authController.js
This PR fixes an issue related to a missing `query` parameter
=> fix: add empty query object to fix default destructuring, resolves #2386

client/src/Pages/Infrastructure/Details/Components/StatusBoxes/index.jsx, client/src/locales/en.json
There was a duplicate `monitorStatus` objet in the locale file leading to a render problem on the uptime page.
=> hotfix: duplicate strings, remove uptime percentage

client/src/Hooks/useNotifications.js, client/src/Pages/Notifications/index.jsx, client/src/Utils/NetworkService.js
This PR updates notificaiton methods to use team ID from JWT instead of accepting a parameter
=> fix: remove team id from notifications

client/src/Hooks/useBulkMonitors.js, server/controllers/monitorController.js, server/controllers/notificationController.js, server/db/mongo/modules/diagnosticModule.js, server/db/mongo/modules/monitorModule.js, server/db/mongo/modules/monitorModuleQueries.js, server/routes/notificationRoute.js
This PR removes team ID parameters from FE requests and instead fetches teamID from the user's token
It also standardizes parameters used in access DB layer instead of passing the whole request object.
=> fix: monitors remove team ID parameters

client/src/Pages/Infrastructure/Monitors/index.jsx, client/src/Pages/Maintenance/MaintenanceTable/index.jsx, client/src/Pages/Maintenance/index.jsx, client/src/Pages/Uptime/Monitors/index.jsx
The `rowsPerPage` var is not safely extracted form the redux state.  Add optional chaining and defautl value to safely access a `rowsPerPage` value on load.
=> hotfix: safe rowsPerPage access

client/src/Hooks/monitorHooks.js, client/src/Pages/Infrastructure/Details/index.jsx
Infrastructure Details page was not using universal details header:
=> fix: add universal header to infra details

client/src/Pages/Incidents/index.jsx
When visiting the incidents page from a link on the details page the specified monitor is not loaded.
This PR impelemnts loading a seleceted monitor from URL params if specified on the incidents page.
Incidents page now loads correctly.
=> fix: load monitor from params if present

client/src/Components/Layouts/AppLayout/index.jsx
This PR updates the BG component to not render the background SVG in light mode.
=> fix: don't render bg svg on light mode

client/src/Utils/i18n.js
This PR adds a flag to the i18n implementation to ignore empty strings
=> fix: translations ignore empty strings

client/src/Components/TabPanels/Account/TeamPanel.jsx, server/controllers/inviteController.js, server/service/emailService.js, server/utils/logger.js
This PR adds a verify function to check if the email transport is configured or not before attempting to send an email
=> fix: verify transport before sending email
