bluewave-labs/Checkmate

- Server/package-lock.json
- Server/package.json
Added "dev" run config to package.json, added nodemon@3.1.0 to dev dependencies for backend
> Add nodemon and dev run config for backend server

- README.md
Some basic instructions for getting the project up and running.
> Added basic installation and startup info to readme

- Client/index.html
- Client/package-lock.json
- Client/package.json
- Client/src/App.jsx
- Client/src/Components/Dropdown/index.css
- Client/src/Components/Dropdown/index.jsx
- Client/src/Components/DropdownTeamMember/index.css
- Client/src/Components/DropdownTeamMember/index.jsx
- Client/src/Components/NavBar/index.css
- Client/src/Components/NavBar/index.jsx
- Client/src/Layouts/HomeLayout/index.css
- Client/src/Layouts/HomeLayout/index.jsx
- Client/src/Pages/Home/index.css
- Client/src/Pages/Home/index.jsx
- Client/src/Pages/Login/index.css
- Client/src/Pages/Login/index.jsx
- Client/src/Pages/NotFound/index.css
- Client/src/Pages/NotFound/index.jsx
- Client/src/Pages/ReadMe.md
- Client/src/Pages/Register/index.css
- Client/src/Pages/Register/index.jsx
- Client/src/Utils/ReadMe.md
- Client/src/index.css
- Client/src/main.jsx
Created routing structure using react-router-dom and added some links and updated the folder structure.
> Updated the root structure of Client side

- Client/src/Components/Link/index.jsx
- Client/src/Pages/Home/index.jsx
- Client/src/Utils/Theme.js
Added a Link component, I only see a tertiary link in the figma doc, so I've only provided style for the tertiary link at the moment.
> Added a link component, currently only have tertiary style

- Server/controllers/authController.js
- Server/controllers/monitorController.js
- Server/db/MongoDB.js
- Server/models/user.js
- Server/validation/joi.js
- Updated the user model, added firstname and lastname fields,
- Updated joi schema, split the authValidation into loginValidation and registerValidation,
- Added logger docs,
- Updated MongoDB file, deselected password when returning user.
> update on joi schema, added logger docs, and updated user model

- README.md
- Server/controllers/authController.js
- Server/db/FakeDb.js
- Server/db/MongoDB.js
- Server/models/user.js
- Server/routes/authRoute.js
Added a login route and some minor refactoring in DB and auth controller
> Added login route, updated readme

- README.md
- Server/controllers/authController.js
- Server/controllers/monitorController.js
- Server/db/FakeDb.js
- Server/index.js
- Server/middleware/jwtVerification.js
- Server/middleware/verifyJWT.js
- Server/package-lock.json
- Server/package.json
Register and Login routes now issue and return a JWT with user info encoded, the frontend will need this for display and requests that need user ID.
There is a JWT verification middleware that can be added to any route or router to protect the route/routes.  The middleware also adds the User model to the `request` object so we have access to it in the protected route.
> Feat/jwt resolves #41

- Client/src/App.jsx
- Client/src/Pages/Home/index.jsx
- Client/src/Pages/Incidents/index.jsx
- Client/src/Pages/Integrations/index.jsx
- Client/src/Pages/Monitors/index.jsx
- Client/src/Pages/Settings/index.jsx
- Client/src/Pages/Status/index.jsx
…, and removed demo components from home page #45
> Added subroutes to homelayout and created basic components resolves #45

- Client/src/Components/NavBar/index.jsx
This is closer to match the overall sought after design
> Refactored the Navbar with an avatar and a full bar.

- README.md
I went ahead and linked server endpoints in the README in the layout that was shown in issue #62 
Let me know if this would suffice or should we make further updates?
> Add Server endpoints to ToC in README

- Server/controllers/monitorController.js
- Server/db/MongoDB.js
- Server/index.js
- Server/middleware/verifyOwnership.js
- Server/models/user.js
- Server/routes/monitorRoute.js
- package-lock.json
Added middleware for verifying ownership of documents
Some minor bugfixes in monitor routes
> Added document ownership middleware, resovles #59

- README.md
- Server/controllers/authController.js
- Server/controllers/monitorController.js
- Server/index.js
- Server/middleware/handleErrors.js
- Server/middleware/verifyJWT.js
- Server/middleware/verifyOwnership.js
Added error handling middleware and documentation
> Feat/error handler, resolves #64

- README.md
- Server/controllers/authController.js
- Server/db/MongoDB.js
- Server/index.js
- Server/middleware/handleErrors.js
- Server/middleware/verifyOwnership.js
- Server/models/user.js
- Server/routes/authRoute.js
- Server/validation/joi.js
> Feat/update user, resolves #58

- README.md
- Server/controllers/alertController.js
- Server/db/MongoDB.js
Added DB operations for `Alerts`
> Feat/alert db resolves #75

- Client/src/Components/DashboardMenu/index.css
- Client/src/Components/DashboardSidebar/index.css
- Client/src/Components/DashboardSidebar/index.jsx
- Client/src/Layouts/HomeLayout/index.css
- Client/src/Layouts/HomeLayout/index.jsx
Implemented the sidebar component and then added it to the home screen layout.
> Implemented the sidebar component

- Client/package-lock.json
- Client/package.json
- Client/src/Components/Button/index.jsx
- Client/src/Components/Section/index.jsx
- Client/src/Features/Monitors/monitorsSlice.js
- Client/src/Pages/Demo/Demo.jsx
- Client/src/main.jsx
- Client/src/store.js
- Server/index.js
Updated `Button` component to accept an `onClick` prop for passing a function
Added Redux Toolkit to the project:
* Added application root store
* Added slice for handling monitors
* Added a demo of Redux functionality to the /demo route for testing
* Added Axios for http requests
> Set up Redux Toolkit, Added redux demo to /demo route

- README.md
- Server/index.js
- Server/package-lock.json
- Server/package.json
- Server/utils/sendEmail.js
Changed the emailing service to `SendGrid` from `Twilio`. Tested the service.
> Implemented the emailing service

- Client/src/Pages/Register/index.jsx
Individual field validation was missing from registration page, not sure what happened to it.
Fields will now update their error state as information is entered
> Added individual field validation for register page

- Client/package-lock.json
- Client/src/Features/Auth/authSlice.js
- Client/src/Layouts/HomeLayout/index.jsx
- Client/src/Pages/Login/index.jsx
- Client/src/Pages/Register/index.jsx
- Client/src/Validation/validation.js
Post login request to backend, store returned user in redux store
> Feat/connect login, resolves #108

- Client/src/App.jsx
- Client/src/Pages/SetNewPassword/index.jsx
- README.md
- Server/controllers/authController.js
- Server/db/MongoDB.js
- Server/models/RecoveryToken.js
- Server/routes/authRoute.js
- Server/service/jobQueue.js
- Server/utils/sendEmail.js
Implemented backend routes for forgot password flow
1.  `POST /recovery/request` - Requests a recovery token from the backend, 10 minute expiration
2. `POST /recovery/validate` - Validates a recovery token issued from the backend
3. `POST /recovery/reset` - Sets `User` password to new password
> Feat/forgot password, resolves #121

- Server/controllers/authController.js
- Server/controllers/monitorController.js
- Server/index.js
- Server/package-lock.json
- Server/package.json
- Server/service/jobQueue.js
Used Axios to get http status from target monitors
Jobs are now added to the queue when a monitor is created
Jobs are now removed from the queue when a monitor is deleted
> Implemented HTTP(s) Request, added add and delete to and from job queue, resolves #134

- Server/index.js
- Server/models/Monitor.js
- Server/package-lock.json
- Server/package.json
- Server/service/jobQueue.js
- Server/validation/joi.js
Monitors can now have a type specified, currently
* ping
* http
JobQueue will handle these two types appropriately.
Added a cleanup method for the JobQueue
> Implemented ping type for monitors, added cleanup for job queue, resolves #136

- Server/service/jobQueue.js
- Server/service/networkService.js
Refactored network operations to a service
> Implemented network service, resolves #145

- Client/src/App.css
- Client/src/Components/DashboardSidebar/index.css
- Client/src/Components/NavBar/index.jsx
- Client/src/Layouts/HomeLayout/index.css
- Client/src/Layouts/HomeLayout/index.jsx
- Client/src/index.css
Changed the navbar and sidebar to be sticky, restructured home-layout, now main-content spans the full width of the page and the content is aligned at the top of the element. No more margins. Might need to look over your individual pages and make sure the padding/margins of the components you are working on are good.
> Implemented flexbox styling for root layout, #146

- Client/src/Features/Monitors/monitorsSlice.js
- Client/src/Pages/Demo/Demo.jsx
* Implemented Async Thunk to get monitors by userID
* Need to do one of:
* Use token in local storage for equest
* Use token in auth state (requires persistence)
* Combination, use token in auth state if it exists, if not check local storage
> Implemented async thunk for getMonitorsByUserId, resolves #161

- Client/package-lock.json
- Client/package.json
- Client/src/main.jsx
- Client/src/store.js
Added redux-persist to handle persisting redux state.
I'd like to open this one up for disucssion, I've never used `redux-persist` before but it looks like it will cover our needs.
If anyone has opinions or suggestions around this please let everyone know.
> Added and configured redux-persist, resolves #164

- Client/src/Components/Avatar/index.jsx
- Client/src/Components/TabPanels/ProfileSettings/PasswordPanel.jsx
- Client/src/Components/TabPanels/ProfileSettings/ProfilePanel.jsx
- Client/src/Components/TextFields/Password/PasswordTextField.jsx
- Client/src/Pages/Settings/index.css
- Client/src/Validation/validation.js
- Client/src/index.css
Refactored input, avatar elements and added some validation.
> Refactor Profile Settings elements with their respective components, #172

- Client/src/App.jsx
- Client/src/Components/Charts/BarChart/BarChart.jsx
- Client/src/Components/Charts/Servers/ServerStatus.jsx
- Client/src/Components/CurrentMonitors/index.jsx
- Client/src/Components/HostsTable/index.jsx
- Client/src/Features/Monitors/monitorsSlice.js
- Client/src/Layouts/HomeLayout/index.jsx
- Client/src/Pages/Monitors/CurrentStats.jsx
- Client/src/Pages/Monitors/index.jsx
- Server/service/networkService.js
This PR connects the monitor page to the backend and display actual data from monitors.
I apologize for the size of the PR, but there were quite a few interelated components that had to be updated together.
Please take your time to review.
I also included normalization for the data checks.  I believe this is probably best done on the backend to keep client performance as high as possible, so we can think about refactoring this in the next PR.
[Source for normalization functinon](https://en.wikipedia.org/wiki/Feature_scaling#Rescaling_(min-max_normalization)), please double check I've implemented this properly.
PR from the air! :airplane:
> Feat/monitor to backend, resolves #160

- Client/src/Components/NavBar/index.jsx
- Client/src/Features/Auth/authSlice.js
- Client/src/Features/Monitors/monitorsSlice.js
Auth state now cleared out when Logout is selected from the navbar
> Implemented logout funcationality, resolves #178

- Client/package-lock.json
- Client/src/App.jsx
- Client/src/Components/NavBar/index.jsx
- Client/src/Components/ProtectedRoute/index.jsx
- Client/src/Features/Monitors/monitorsSlice.js
- Client/src/Pages/Login/index.jsx
NavBar now reflects user's information
> Feat/nav state, resovles #177

- Client/package-lock.json
- Client/src/App.jsx
- Client/src/Components/NavBar/index.jsx
- Client/src/Components/ProtectedRoute/index.jsx
- Client/src/Features/Monitors/monitorsSlice.js
- Client/src/Pages/Login/index.jsx
Implemented a protected route component
Fixed some redirects to point to `/login` instead of `/`
> Feat/protected routes, resolves #180

- Client/src/Features/Auth/authSlice.js
- Client/src/Features/Monitors/monitorsSlice.js
> Fixed error handling bug in redux slices

- README.md
- Server/controllers/authController.js
Also updated README with new env var information
> Added token TTL env variable with default of 2 hours, resolves #163

- Client/src/Pages/Login/index.jsx
- Client/src/Pages/Monitors/CurrentStats.jsx
Monitor page now displays correct username
> Added authstate to CurrentStats, displays username correctly, resolves #185

- Client/src/Components/Checkbox/Checkbox.css
- Client/src/Components/Checkbox/CustomizableCheckbox.jsx
- Client/src/Components/Dropdown/index.jsx
- Client/src/Components/RadioButton/index.jsx
- Client/src/Components/TextFields/Flexibile/FlexibileTextField.jsx
- Client/src/Pages/Monitors/CreateNewMonitor.jsx
- Client/src/Pages/Monitors/index.css
- Client/src/Pages/Monitors/index.jsx
- Client/src/index.css
the Create New Monitor page is complete except dropdowns since I could not make it work to get its value or give it list of options, although I added a text field as a placeholder for dropdowns for now. And, your able to capture input values, too.
> Create new monitor without dropdowns

- Client/src/Components/TabPanels/ProfileSettings/ProfilePanel.jsx
- Client/src/Components/TextFields/Email/EmailTextField.jsx
- Client/src/Components/TextFields/Text/TextField.jsx
- Client/src/Features/Auth/authSlice.js
- Client/src/Pages/Settings/index.css
Form fields will now update with the user's data. Updating profile fields now works. Also, fixed sizing issue from register/login pages.
> Integrated redux, #173 and #182

- Client/src/Components/TabPanels/ProfileSettings/ProfilePanel.jsx
- Client/src/Components/TextFields/Image/index.css
- Client/src/Components/TextFields/Image/index.jsx
- Client/src/Pages/Demo/Demo.jsx
- Client/src/Utils/Theme.js
Will add proptypes and jsdocs to the ImageField Component once I iron out its parameters. Atm only the id is being passed. Wanted to get the base design out of the way to start working on the logic behind and tie it to the redux store.
> Initial Design for the Upload Picture Modal

- README.md
> Fixed error in docker image location in docs

- Client/src/Components/TabPanels/ProfileSettings/ProfilePanel.jsx
- Client/src/Pages/Settings/index.css
- Client/src/Validation/validation.js
Addressed some minor styling issues and adjusted the validation schema based on our meeting.
> Fixed some small styling issues and validation schema

- Client/src/Pages/CreateNewMonitor/index.jsx
Users will be redirected to Monitors page on successful monitor creation
> Redirected user to Monitors page after adding a new monitor

- Client/src/Components/ConfigBox/index.css
- Client/src/Components/RadioButton/index.css
- Client/src/Components/RadioButton/index.jsx
- Client/src/Components/TabPanels/Account/PasswordPanel.jsx
- Client/src/Components/TabPanels/Account/ProfilePanel.jsx
- Client/src/Components/TabPanels/Account/TeamPanel.jsx
- Client/src/Components/TextFields/Flexibile/FlexibileTextField.jsx
- Client/src/Components/TextFields/Flexibile/flexibileTextField.css
- Client/src/Pages/Account/index.jsx
- Client/src/Pages/CreateNewMonitor/index.css
- Client/src/Pages/CreateNewMonitor/index.jsx
- Client/src/Utils/Theme.js
- Client/src/Validation/validation.js
- Client/src/index.css
Only the code not commented was refactored. Will refactor the rest as we go and add the remaining features. 
Some issues: 
- Validation is not finalized
- The select dropdown will cover up the select field if there isn't sufficient space to expand under. Not really sure if this will affect us once all the features are added but worth mentioning regardless.
> Refactored create monitor page styling using @mui components, resolves #218

- Server/models/user.js
- Server/validation/joi.js
Added roles field to `User`, two acceptable values
- user
- admin
> Added role field to User model, resolves #233

- Client/src/Features/Auth/authSlice.js
- Server/db/MongoDB.js
- Server/middleware/handleErrors.js
- Server/models/user.js
- Server/package-lock.json
- Server/package.json
- Server/routes/authRoute.js
- Server/validation/joi.js
Backend implementation for image upload
- Stores image bytes directly to DB
> Feat/image upload, resolves #221

- Client/src/Components/ProgressBars/index.css
- Client/src/Components/ProgressBars/index.jsx
- Client/src/Components/TabPanels/Account/ProfilePanel.jsx
- Client/src/Components/TextFields/Image/index.css
- Client/src/Components/TextFields/Image/index.jsx
- Client/src/Validation/validation.js
I plan to refactor the code to redux on my next pr. That should get rid of most of the useStates and make the code easier to read.
> Added validation to picture uploads, resolves #213

- Server/controllers/authController.js
- Server/db/MongoDB.js
- Server/routes/authRoute.js
- Server/utils/messages.js
- Server/validation/joi.js
`/api/v1/auth/users/admin` will return `true` or `false` if a user admin account exists or does not , respectively.
> Feat/check admin, resolves #241

- Client/src/App.jsx
- Client/src/Pages/Login/index.jsx
- Client/src/Pages/Register/index.jsx
WIP
Redirects all work, however it might be better to refactor this into a middleware route like `ProtectedRoute` just for the `/login` and `/register` routes.
> Feat/redirect on no admin, resolves #232

- Server/db/MongoDB.js
- Server/routes/authRoute.js
- Server/validation/joi.js
Added `profileImage` to update user endpoint
> Added image bytes to update user profile, resolves #247

- Client/src/Pages/Register/index.jsx
- Client/src/Validation/validation.js
Admin role added to user created by the Registration page
> Added admin role to registration, resolves #249

- Server/models/Check.js
- Server/models/Monitor.js
Monitor now has a status that is updated whenever a new check is created.
Logic in place for sending an alert if status changes from up to down or down to up.
> Monitor now has a status, status will be updated on new check, #235

- Server/models/Check.js
Forgot to update monitor status, fixed
> Update monitor status

- Client/src/Pages/Incidents/index.jsx
The only thing left should be the pagination at the bottom and then we should be able to close this issue.
> Incidents page refactor. 

- Server/db/MongoDB.js
Remove image from user before returning it
> Removed profile image from user before returning it, #259

- Server/db/MongoDB.js
> Fixed select error in getUserByEmail

- Client/src/Components/Alert/index.css
- Client/src/Components/Alert/index.jsx
- Client/src/Components/TabPanels/Account/PasswordPanel.jsx
- Client/src/Pages/Account/index.css
- Client/src/Pages/Demo/Demo.jsx
- Client/src/Utils/Theme.js
Refactored the `Announcement` component used in `Password` page to stop `closeToast` error from occuring.
> Alert component, resolves #279

- Client/src/Pages/CreateNewMonitor/index.css
- Client/src/Pages/CreateNewMonitor/index.jsx
Added button to navigate back to `/monitors` from `/monitors/create`.
> Added navigation button, resolves #258

- Server/controllers/authController.js
- Server/db/MongoDB.js
- Server/models/user.js
- Server/package-lock.json
- Server/package.json
- Server/utils/imageProcessing.js
Generate and save avatar sized image (64 * 64) on save and update
> Generate avatar image on register or update if an image is included, #259

- Client/src/Components/MonitorTable/index.css
- Client/src/Components/MonitorTable/index.jsx
- Client/src/Components/TextFields/Search/SearchTextField.jsx
- Client/src/Pages/Monitors/index.jsx
- Client/src/assets/icons/search.svg
Updated monitors pagination to match Figma design.
> Monitors pagination styling, resolves #295

- Server/controllers/authController.js
- Server/db/MongoDB.js
- Server/utils/utils.js
- Server/validation/joi.js
Added flag to check for image delete
> Added delete image profile functionality to update user, #297

- Client/src/Features/Auth/authSlice.js
- Client/src/Features/Monitors/monitorsSlice.js
- Client/src/Pages/ForgotPassword/index.jsx
- Client/src/Pages/Login/index.jsx
- Client/src/Pages/Register/index.jsx
- Client/src/Pages/SetNewPassword/index.jsx
- Client/src/Utils/axiosConfig.js
- Client/src/main.jsx
Added an axios instance with an interceptor for 401 requests.
If a 401 is returned by the server the auth state will be cleared and the user will be booted to the login screen
> Added configured axios instance with 401 interceptor, resolves #299

- Client/src/Components/TabPanels/Account/ProfilePanel.jsx
- Client/src/Features/Auth/authSlice.js
Finalized the frontend image deletion logic.
> Image deletion, resolves #297

- Client/src/Components/TabPanels/Account/ProfilePanel.jsx
- Client/src/Features/Auth/authSlice.js
Connected backend to redux auth slice.
> Account deletion

- Server/controllers/authController.js
- Server/db/MongoDB.js
- Server/models/user.js
- Server/validation/joi.js
- Added helper method to extract auth from headers
- Added validaiton for password to updating users
- Added mongoose middleware to handle hashing updated passwords
- Added password change logic to update user endpoint
> Implemented update password functionality, #214

- Client/src/App.jsx
- Client/src/Pages/Account/index.jsx
- Client/src/Pages/Login/index.jsx
- Client/src/Pages/Register/index.jsx
Added toast alerts to login/register pages and move `ToastContainer` to top of the page so the alerts can be displayed everywhere in the app.
> Added toast alerts to login/register pages, resolves #147

- Client/src/Pages/Register/index.jsx
One time registration page now shows create admin account
> Changed text for create account, resolves #314

- Client/src/Components/BasicTable/index.jsx
- Client/src/Components/MonitorTable/index.jsx
This table builds of @Skorpios604 's Status Table to build a generic table that can display any number of columns and rows
**TODO Currently Unstyled**
Table takes input arrays of objects in this format:
**headers**
|Name| Type|Note|
|---|---|---|
|id|number|Unique ID|
|name|string|Header name|
Example: 
```
headers: [
{id:1, name: "Col 1},
{id:2, name: "Col 2}
]
```
**rowItems**
|Name| Type|Note|
|---|---|---|
|id|number| Unique ID|
|data|React Node| Any valid react node|
Example: 
```
rowItems  = [
{id: 1, data: <span>Row 1, col 1</span>},
{id: 2, data: <span>Row 1, col 2</span>},
{id: 3, data: <span>Row 2, col 1</span>},
{id: 4, data: <span>Row 2, col 2</span>}
]
```
Rows will be arranged under their respective columns according to the number of headers.
> Implemented a basic table that takes a standard arrangement of data

- Server/routes/pageSpeedCheckRoute.js
> correcetd route and method for delete route

- Client/src/Pages/Details/index.jsx
- Client/src/main.jsx
Added StatBox component to dipslay stats
Calculated stats for StatBox
Added StatusLabel to table
> Add status label and StatBox component

- Client/src/Components/TabPanels/Account/PasswordPanel.jsx
- Client/src/Components/TabPanels/Account/ProfilePanel.jsx
- Client/src/Pages/Auth/CheckEmail.jsx
- Client/src/Pages/Auth/ForgotPassword.jsx
- Client/src/Pages/Auth/Login.jsx
- Client/src/Pages/Auth/Register.jsx
- Client/src/Pages/Auth/SetNewPassword.jsx
- Client/src/Utils/toastUtils.jsx
I realized the call function for toast notifications was a little counter intuitive so I simplified it.
> Simplified toast function call

- Server/index.js
- Server/package-lock.json
- Server/package.json
- Server/service/emailService.js
- Server/templates/employeeActivation.mjml
- Server/templates/noIncidentsThisWeek.mjml
- Server/templates/passwordReset.mjml
- Server/templates/serverIsDown.mjml
- Server/templates/serverIsUp.mjml
- Server/templates/welcomeEmail.mjml
Nodemailer is Implemented
Email templated are dynamic in variables, but the code inside the route for
```
app.use("/api/v1/mail", (req, res) => {
// my code
})
```
is hard coded, so it needs to be modified to be dynamic according to the situation and the response for the user.
Results:
> Nodemailer implemented

- Client/src/Pages/Auth/Register/Register.jsx
> Fix refactoring bug, shadowing variable

- Server/index.js
- Server/service/emailService.js
Refactored email service to use modern JS
Refactored repetitive code
Refactor to use SMTP
> Refactored email service for modernity and clarity

- Client/src/App.jsx
- Client/src/Components/RadioButton/index.css
- Client/src/Components/TabPanels/Account/TeamPanel.jsx
- Client/src/Pages/Monitors/Configure/index.css
- Client/src/Pages/Monitors/Configure/index.jsx
- Client/src/Pages/Monitors/CreateMonitor/index.jsx
- Client/src/Pages/Monitors/Details/index.jsx
- Client/src/Validation/validation.js
Added monitors page.
Currently missing:
- submit function
> Configure monitors page

- Server/db/MongoDB.js
- Server/index.js
- Server/package-lock.json
- Server/package.json
- Server/service/emailService.js
Changed sort order of checks to consitently be newest -> oldest.
We can decide if we want charts to display data from newest -> oldest or oldest -> newest and deal with that on the frontend.
> Fix/sort order, resolves #397

- Client/src/Components/TabPanels/Account/TeamPanel.jsx
Added invite request from frontend.
> Invite request, resolves #392

- Client/src/Components/Inputs/Field/index.jsx
- Client/src/Components/Link/index.jsx
- Client/src/Pages/Settings/index.css
- Client/src/Pages/Settings/index.jsx
Added components and styling to settings page. No functionality yet.
> Settings page

- Server/service/emailService.js
Fixed bug in email service after upgrading to 5.0 alpha
> Fixed unawaited promise in email service

- Client/src/index.css
This should disable the ripple effects from all components. Not all @mui components have the `disableRipple` prop.
> Disable ripple effects

- Client/src/Components/BasicTable/index.css
- Client/src/Components/BasicTable/index.jsx
- Client/src/Components/TabPanels/Account/TeamPanel.jsx
- Client/src/Pages/Incidents/index.css
- Client/src/Pages/Incidents/index.jsx
- Client/src/Utils/Theme.js
- Client/src/index.css
Select dropdown styling isn't completed, need to create reusable component first.
> Incidents page styling

- Client/src/Components/Inputs/Select/index.css
- Client/src/Components/Inputs/Select/index.jsx
- Client/src/Components/TabPanels/Account/TeamPanel.jsx
- Client/src/Pages/Account/index.css
- Client/src/Pages/Incidents/index.jsx
- Client/src/Pages/Monitors/Configure/index.css
- Client/src/Pages/Monitors/Configure/index.jsx
- Client/src/Pages/Monitors/CreateMonitor/index.css
- Client/src/Pages/Monitors/CreateMonitor/index.jsx
- Client/src/Pages/Settings/index.jsx
Built select component and added styling. The `items` prop needs to take in an array of objects, with `_id` (value) and `name` (text to display) fields required.
> Select component

- Server/service/networkService.js
> Forgot to call longAndStoreCheck

- Client/src/Components/Inputs/Field/index.jsx
- Client/src/Pages/Monitors/CreateMonitor/index.css
- Client/src/Pages/Monitors/CreateMonitor/index.jsx
- Server/models/Monitor.js
Design will likely change, just added a placeholder button toggle for now.
> Added http/https toggle

- .coderabbit.yaml
Hopefully reduces # of comments
> Updated coderabbit.yaml

- Server/controllers/monitorController.js
- Server/db/mongo/MongoDB.js
- Server/db/mongo/modules/notificationModule.js
> Add DB operations for notifications

- Client/src/Components/Inputs/Field/index.jsx
- Client/src/Features/UptimeMonitors/uptimeMonitorsSlice.js
- Client/src/Pages/Monitors/Configure/index.jsx
Removed/disabled editing of features that should not be editable
Connected Save and Delete buttons
Fetch moniotrs on successful update to refresh UI
> Feat/fe/connect config, resolves #497

- Server/controllers/authController.js
When a user is deleted, all their monitors and associated checks and notifications are deleted
> Delete notifcations when a user is deleted

- Server/db/mongo/modules/monitorModule.js
`getMonitorsByUserId` and `getMonitorById` include associated Notifications now
> Add notifications to monitors before returning

- Client/src/Components/Avatar/index.jsx
- Client/src/Components/BasicTable/index.css
- Client/src/Components/Button/index.jsx
- Client/src/Components/Charts/Servers/ServerStatus.jsx
- Client/src/Components/Inputs/Field/index.css
- Client/src/Components/Inputs/Select/index.css
- Client/src/Pages/Account/index.css
- Client/src/Pages/Account/index.jsx
- Client/src/Pages/Auth/Login.jsx
- Client/src/Pages/Auth/index.css
- Client/src/Pages/Monitors/Details/index.jsx
- Client/src/Pages/PageSpeed/index.css
- Client/src/Pages/PageSpeed/index.jsx
- Client/src/Utils/Theme.js
- Client/src/index.css
Disclaimer alert: Text appearance has changed so there might be some inconsistencies with the Figma design here and there, keep an eye out if you see any. (mostly `font sizes` or font weights`)
> Updated default font and some small styling changes

- Client/src/Features/Auth/authSlice.js
- Client/src/Features/UptimeMonitors/uptimeMonitorsSlice.js
- Server/routes/authRoute.js
- Server/routes/monitorRoute.js
Used `put` and `delete` rest verbs where appropriate
> Fix rest verbs

- Server/models/PageSpeedCheck.js
- Server/service/networkService.js
Added audit stats to pagespeed check
> Add required stats to PagespeedCheck model

- Client/src/Pages/PageSpeed/Details/index.css
- Client/src/Pages/PageSpeed/Details/index.jsx
- Client/src/Utils/Theme.js
There's some edge cases to be tested but other than that the pie chart is about fully functional.
> Pagespeed pie chart 

- Server/controllers/queueController.js
- Server/index.js
- Server/service/jobQueue.js
Queue was getting stuck in waiting state after Redis connection closed, ie on server redeploy.
I _believe_ the solution is a better cleanup process, so I've improved what we've got so far.  We will monitor for further situations where the queue gets stuck.
Also added a minimum of 5 workers as we have some longer runnig jobs now, we don't want to be stuck waiting on a single worker.
> Added more logging, improved cleanup

- Client/src/Pages/Monitors/index.jsx
> Got rid of the redundant word "back" here. 

- Client/src/Pages/Incidents/index.jsx
- Client/src/Pages/Monitors/Configure/index.jsx
- Client/src/Pages/Monitors/Details/index.css
- Client/src/Pages/Monitors/Details/index.jsx
- Client/src/Pages/Monitors/index.jsx
- Client/src/Pages/PageSpeed/Details/index.jsx
- Client/src/Pages/PageSpeed/index.jsx
- Client/src/index.css
The PR may seem a tiny bit more intimidating than it actually is 😂 . A lot of the code was re-layered, which resulted in the high # of lines changed.
Resolves #550
> Loading skeletons

- Client/src/Components/BasicTable/index.jsx
- Client/src/Pages/Monitors/Details/index.jsx
Separate fetching monitor data for Chart and data for Table.  These two will need to be separate requests in order to fetch
1.  50 checks needed for the chart
2. One page worth of checks for the chart
This will help keep request size down and keep the site performing well
> Prep monitor details page for #567

- Client/src/App.jsx
- Client/src/Components/TabPanels/Account/ProfilePanel.jsx
- Client/src/Features/PageSpeedMonitor/pageSpeedMonitorSlice.js
- Client/src/Pages/Monitors/Configure/index.jsx
- Client/src/Pages/Monitors/index.css
- Client/src/Pages/PageSpeed/Configure/index.css
- Client/src/Pages/PageSpeed/Configure/index.jsx
- Client/src/Pages/PageSpeed/Details/index.jsx
The code is much of the same as the `create pagespeed page`. Updated redux to include thunks for updating and deleting pagespeed monitors.
> Configure pagespeed page

- Client/src/Layouts/HomeLayout/index.css
- Client/src/Pages/Maintenance/CreateMaintenanceWindow/index.css
- Client/src/Pages/Maintenance/CreateMaintenanceWindow/index.jsx
- Client/src/index.css
> completing create new  maintenance window (no-repeat) UI

- SECURITY.md
Create `SECURITY.md` same as [Bluewave Onboarding](https://github.com/bluewave-labs/bluewave-onboarding/blob/master/SECURITY.md) and [Bluewave HRM](https://github.com/bluewave-labs/bluewave-hrm/blob/main/SECURITY.md)
> docs(security): add SECURITY.md

- Client/src/Components/NavBar/index.jsx
- Server/controllers/authController.js
- Server/db/mongo/modules/userModule.js
- Server/middleware/verifyJWT.js
- Server/models/user.js
- Server/routes/authRoute.js
- Server/utils/messages.js
This PR should prevent users from being able to login in mulitple clients
> Feat/login security, resolves #583

- Client/src/Components/NavBar/index.jsx
- Server/controllers/authController.js
- Server/db/mongo/MongoDB.js
- Server/db/mongo/modules/userModule.js
- Server/middleware/verifyJWT.js
> Decoupled JWT from DB, resolves #590

- Client/src/Pages/Auth/ForgotPassword.jsx
- Client/src/Pages/Auth/Login.jsx
- Client/src/Pages/Auth/index.css
Looks much the same as the other auth pages.
Resolves #593
> Forgot password page

- Client/src/Pages/Auth/CheckEmail.jsx
- Client/src/Pages/Auth/index.css
Looks much the same as the other auth pages.
> Check email page

- Server/controllers/authController.js
- Server/db/mongo/modules/userModule.js
Refactored endpoint to avoid having to create mock request objects
> Refactored  endpoint

- Client/src/Pages/Monitors/Details/index.jsx
- Server/controllers/monitorController.js
- Server/db/mongo/MongoDB.js
- Server/db/mongo/modules/checkModule.js
- Server/db/mongo/modules/monitorModule.js
- Server/routes/monitorRoute.js
- Server/utils/messages.js
> Refactored monitor details, resolves #596

- Client/src/Pages/Auth/SetNewPassword.jsx
- Client/src/Pages/Auth/index.css
Looks much the same as the other auth pages.
> Set password page

- Client/src/Pages/Monitors/Details/index.jsx
- Client/src/Pages/PageSpeed/Details/index.jsx
- Server/db/mongo/modules/monitorModule.js
> Refactor pagespeed details to use stats endpoint

- Server/db/mongo/modules/monitorModule.js
> Fix spelling.

- Client/src/Components/Check/Check.jsx
- Client/src/Components/Check/check.css
- Client/src/Pages/Auth/CheckEmail.jsx
- Client/src/Pages/Auth/ForgotPassword.jsx
- Client/src/Pages/Auth/Login.jsx
- Client/src/Pages/Auth/NewPasswordConfirmed.jsx
- Client/src/Pages/Auth/Register/Register.jsx
- Client/src/Pages/Auth/SetNewPassword.jsx
- Client/src/Pages/Auth/index.css
- Client/src/index.css
Didn't feel like it was necessary to account for multiple breakpoints since the authentication pages are relatively simple and don't display much content. Let me know what you all think.
> Responsive design

- Client/src/Pages/Monitors/Details/index.jsx
- Server/db/mongo/modules/monitorModule.js
- Server/validation/joi.js
> Refactored getMonitorStats for clarity

- README.md
> Added better quickstart for devs

- Client/src/Pages/PageSpeed/Details/index.jsx
> Fixed mutation of data

- Client/src/Components/Charts/MonitorDetailsAreaChart/index.jsx
> Removed erorr squash in Monitor Details chart

- Client/src/Components/Fallback/index.jsx
- Client/src/Layouts/HomeLayout/index.css
> Added background pattern to fallback pages

- Client/package-lock.json
- Client/src/Pages/Monitors/index.jsx
- Server/package-lock.json
- Server/package.json
Reverts bluewave-labs/bluewave-uptime#637
> Revert "Added sorting ability by status"

- Server/controllers/monitorController.js
- Server/middleware/handleErrors.js
- Server/middleware/verifyOwnership.js
> Updated parameters passed to  for certificate check

- Client/src/Components/Sidebar/index.jsx
- Client/src/Pages/Monitors/index.jsx
- Server/controllers/authController.js
- Server/middleware/verifyJWT.js
- Server/models/user.js
- Server/routes/authRoute.js
- Server/utils/messages.js
This feature wasn't especially useful and violates REST principles to some degree
> Revert double login prevention

- Client/src/Components/TabPanels/Account/PasswordPanel.jsx
- Client/src/Pages/Account/index.jsx
> Removed sso login banner

- Server/controllers/queueController.js
- Server/index.js
- Server/routes/queueRoute.js
- Server/service/jobQueue.js
> Added metrics endpoint to queue, improved cleanup, improved logging

- Client/src/Pages/Auth/Login.jsx
> Resolve validation error appearing when unrelated issue occurs

- Client/src/Components/BasicTable/index.css
- Client/src/Components/Charts/Servers/serverStatus.css
- Client/src/Components/Sidebar/index.css
- Client/src/Components/Sidebar/index.jsx
- Client/src/Pages/Monitors/index.css
- Client/src/Pages/Monitors/index.jsx
- Client/src/index.css
> Updated color and font weights

- Server/controllers/monitorController.js
> Updated config monitor controller, resolves #656

- Client/src/Pages/NotFound/index.jsx
> Moved title, changed default value, resolves #661

- Client/src/Components/Breadcrumbs/index.css
- Client/src/Components/Breadcrumbs/index.jsx
- Client/src/Pages/Monitors/Configure/index.jsx
- Client/src/assets/icons/right-arrow.svg
> Breadcrumbs component

- Client/src/Components/Breadcrumbs/index.css
- Client/src/Pages/Monitors/Configure/index.css
- Client/src/Pages/Monitors/Configure/index.jsx
- Client/src/Pages/Monitors/CreateMonitor/index.css
- Client/src/Pages/Monitors/CreateMonitor/index.jsx
- Client/src/Pages/Monitors/Details/index.jsx
- Client/src/Pages/PageSpeed/Configure/index.css
- Client/src/Pages/PageSpeed/Configure/index.jsx
- Client/src/Pages/PageSpeed/CreatePageSpeed/index.css
- Client/src/Pages/PageSpeed/CreatePageSpeed/index.jsx
- Client/src/Pages/PageSpeed/Details/index.css
- Client/src/Pages/PageSpeed/Details/index.jsx
- Client/src/index.css
Added breadcrumbs to:
I removed the bar chart from monitor details page for now since the feature is not fully functional and we're likely going to move its placement and use a different chart library for it.
> Breadcrumbs

- Docker/client.Dockerfile
- Docker/docker-compose.yaml
> Migrate from serve to nginx, resolves #640

- Client/src/Pages/Auth/Login.jsx
> Add redirect to login page if user already logged in, resolves #641

- Client/src/Pages/PageSpeed/Details/index.jsx
> Add null data checks to pagespeed, resolves #618

- Client/src/Pages/Monitors/Details/index.jsx
- Server/db/mongo/modules/monitorModule.js
- Server/utils/dataUtils.js
Mongo document was not parsed correctly for case of single check in the Normalization function.
> Parsed mongo doc correctly in Normalization function, resolves #672

- Client/src/Components/BasicTable/index.css
- Client/src/Components/BasicTable/index.jsx
- Client/src/Pages/Monitors/index.css
- Client/src/Pages/Monitors/index.jsx
- Client/src/assets/icons/left-arrow-double.svg
- Client/src/assets/icons/right-arrow-double.svg
- Client/src/assets/icons/selector-vertical.svg
> Pagination rows

- Client/src/Components/Inputs/Select/index.css
> Fixed select dropdown styling

- Client/src/Components/TabPanels/Account/PasswordPanel.jsx
- Client/src/Components/TabPanels/Account/ProfilePanel.jsx
- Client/src/Components/TabPanels/Account/TeamPanel.jsx
- Client/src/Pages/Account/index.css
> Account tab panels refactor

- Server/validation/joi.js
This PR adds validaiton to the `role` array
> Add validation for roles array, resolves #690

- Client/src/Utils/NetworkService.js
- Server/controllers/authController.js
- Server/service/emailService.js
This PR adds error handling to the `EmailService`
> Add error handling and logging to email service, resolves #691

- Client/src/Pages/Auth/Login.jsx
- Client/src/Pages/Auth/Register/Register.jsx
PR adds links for privacy policy and TOS to the Login and Register pages
> Add TOS and Privacy Policy links, resovles #697

- Docker/client.Dockerfile
- Docker/nginx/default.conf
This PR adds a default config file for nginx to allow for React routing
> Add nginx config

- Client/src/Components/Sidebar/index.jsx
- Client/src/Components/TabPanels/Account/TeamPanel.jsx
> Comment out unused features, #699

- Client/src/Components/Animated/PulseDot.jsx
- Client/src/Components/BasicTable/index.css
- Client/src/Components/Charts/BarChart/index.css
- Client/src/Components/Charts/BarChart/index.jsx
- Client/src/Components/Sidebar/index.jsx
- Client/src/Pages/Monitors/index.jsx
- Client/src/Utils/timeUtils.js
- Client/src/index.css
> Monitor dashboard bar chart

- Client/package-lock.json
- Client/package.json
- Client/src/Components/Inputs/Field/index.jsx
- Client/src/Pages/Maintenance/CreateMaintenanceWindow/index.css
- Client/src/Pages/Maintenance/CreateMaintenanceWindow/index.jsx
- Client/src/Validation/validation.js
- Marshal data and log it
- Create post request
- Send post request to BE
> Marshal data, logging it, creating post req, send to BE

- Server/models/user.js
> Initialize User model to creat index

- Client/src/Components/Sidebar/index.jsx
- Client/src/Components/TabPanels/Account/TeamPanel.jsx
- Client/src/HOC/withAdminCheck.jsx
- Client/src/Pages/Account/index.jsx
- Client/src/Pages/Auth/Login.jsx
- Client/src/Pages/Auth/Register/Register.jsx
- Client/src/Utils/NetworkService.js
- Client/src/Validation/validation.js
- Server/controllers/authController.js
- Server/controllers/inviteController.js
- Server/db/mongo/MongoDB.js
- Server/db/mongo/modules/inviteModule.js
- Server/db/mongo/modules/userModule.js
- Server/index.js
- Server/middleware/verifyAdmin.js
- Server/middleware/verifySuperAdmin.js
- Server/models/InviteToken.js
- Server/models/Team.js
- Server/models/user.js
- Server/routes/authRoute.js
- Server/routes/inviteRoute.js
- Server/validation/joi.js
This is quite a large PR as it is the basis of implementing teams
> Feat/team table, #725

- Client/src/Pages/Maintenance/CreateMaintenanceWindow/index.jsx
- Client/src/Pages/Monitors/Configure/index.jsx
- Client/src/Pages/Monitors/CreateMonitor/index.jsx
- Client/src/Pages/PageSpeed/Configure/index.jsx
- Client/src/Pages/PageSpeed/CreatePageSpeed/index.jsx
- Client/src/Validation/validation.js
> Update all areas where it says friendly name to display name.

- Server/service/networkService.js
- Server/utils/messages.js
This PR adds status codes and messages to all checks
> Add status codes and messages to checks

- Server/controllers/authController.js
This PR removes non-functional code from login route
> Removed unused token code

- Client/src/Pages/Monitors/Details/index.jsx
> Add check for monitor type to abort certificate check if not http type, resolves #720

- Client/src/Components/TabPanels/Account/TeamPanel.jsx
> Add superadmin to admin group in team panel, resolves #741

- Client/src/Features/Auth/authSlice.js
- Client/src/Utils/NetworkService.js
- Server/db/mongo/modules/userModule.js
There was an error in the auth reducer due to the axios refactor some time ago
> Use axios directly for fetching file, resolves #751

- Client/src/Components/Inputs/Field/index.jsx
- Client/src/Pages/Auth/index.css
- Client/src/Pages/Monitors/Configure/skeleton.jsx
- Client/src/Utils/Theme/darkTheme.js
- Client/src/Utils/Theme/lightTheme.js
- Client/src/Utils/toastUtils.jsx
- Client/src/index.css
> Moved toast notif to top right and some other small fixes

- Server/db/mongo/modules/monitorModule.js
This PR adds notificatiosn to the `getMonitorById` endpoint
> Add notifications to single monitor

- Client/src/App.jsx
- Client/src/Features/UptimeMonitors/uptimeMonitorsSlice.js
- Client/src/Pages/Settings/index.jsx
- Client/src/Utils/NetworkService.js
- Server/controllers/checkController.js
- Server/db/mongo/MongoDB.js
- Server/db/mongo/modules/checkModule.js
- Server/routes/checkRoute.js
- Server/validation/joi.js
This PR implements clearing all stats for all monitors by TeamID
> Feat/clear checks, resolves #759

- Client/src/Pages/Monitors/Configure/index.jsx
- Server/controllers/monitorController.js
- Server/db/mongo/modules/monitorModule.js
- Server/models/Monitor.js
Notifications now attached to `Monitor` object for simplifcation
> Notifications added to monitor object

- Client/src/Pages/Monitors/Home/monitorData.jsx
- Server/db/mongo/modules/checkModule.js
- Server/models/Monitor.js
> Adds real percentages to the uptime monitoring dashboard. Fixes #738

- Client/src/Features/UptimeMonitors/uptimeMonitorsSlice.js
> Small spelling error fix.

- Client/src/Components/BasicTable/index.jsx
- Client/src/Features/UI/uiSlice.js
- Client/src/Pages/PageSpeed/index.css
- Client/src/Utils/greeting.jsx
> Added greeting lists and implemented randomizer

- Client/src/Components/TabPanels/Account/TeamPanel.jsx
- Client/src/Features/PageSpeedMonitor/pageSpeedMonitorSlice.js
- Client/src/Features/UptimeMonitors/uptimeMonitorsSlice.js
- Client/src/Pages/Monitors/Configure/index.jsx
- Client/src/Pages/PageSpeed/Configure/index.jsx
- Client/src/Pages/PageSpeed/Configure/skeleton.jsx
- Client/src/Pages/PageSpeed/CreatePageSpeed/index.jsx
- Client/src/Pages/Settings/index.jsx
This PR adds loading states to all buttons that should be disabled while waiting for network operations
> Feat/button loading, resolves #727

- Client/src/Pages/Monitors/Home/MonitorTable/index.jsx
- Client/src/Pages/Monitors/Home/index.jsx
> Fixed monitor state error and added row click back

- Client/src/Pages/Incidents/index.jsx
- Client/src/Pages/Monitors/Home/MonitorTable/index.jsx
- Server/db/mongo/modules/monitorModule.js
> Fixed pagination styling

- Client/src/Features/UptimeMonitors/uptimeMonitorsSlice.js
- Client/src/Pages/PageSpeed/card.jsx
- Client/src/Pages/PageSpeed/index.jsx
- Client/src/Pages/PageSpeed/skeleton.jsx
This PR fixes some issues with the Pagespeed page after updating the redux state
> Pagespeed fixes

- Client/src/Components/Charts/MonitorDetailsAreaChart/index.jsx
- Client/src/Pages/Monitors/Details/Charts/index.jsx
- Client/src/Utils/Theme/darkTheme.js
- Client/src/Utils/Theme/lightTheme.js
- Client/src/index.css
> Fixed dark mode skeleton color

- Client/src/Components/Charts/MonitorDetailsAreaChart/index.jsx
- Client/src/Pages/Monitors/Details/Charts/index.jsx
> Fixed janky bar animations

- Client/src/Pages/PageSpeed/CreatePageSpeed/index.jsx
This PR updates the Create Pagespeed page
> Refactor create pagespeed, resolves #796

- Client/src/Pages/Monitors/Home/index.jsx
> fix unsafe access

- Server/service/jobQueue.js
> Fixed property name for check

- Client/src/Components/Sidebar/index.jsx
- Client/src/Pages/Account/index.jsx
- Client/src/Utils/Theme/darkTheme.js
- Client/src/Utils/Theme/lightTheme.js
> Prevent scrollbar from shifting content

- Client/src/Components/Charts/MonitorDetailsAreaChart/index.jsx
- Client/src/Components/Sidebar/index.jsx
- Client/src/Pages/Monitors/Home/index.jsx
> Fixed minor bugs and updated area tooltip styling

- Client/src/Components/Inputs/Select/index.jsx
- Client/src/Pages/Monitors/Home/MonitorTable/index.jsx
> Prevent content shift 

- Client/src/Pages/PageSpeed/card.jsx
> Remove console.log

- Client/src/Pages/Monitors/Home/actionsMenu.jsx
This PR adds an admin check to the Clone feature
> Add  check to clone option

- Client/src/Pages/PageSpeed/Details/index.jsx
> Pagespeed pulse dot

- Client/src/Pages/Monitors/Home/index.jsx
- Client/src/Pages/Monitors/utils.jsx
- Client/src/Pages/PageSpeed/card.jsx
- Client/src/Pages/PageSpeed/index.css
- Client/src/Pages/PageSpeed/index.jsx
- Server/db/mongo/modules/checkModule.js
> Pagespeed dashboard revamp

- Server/db/mongo/modules/checkModule.js
> Remove duplicate method

- Client/src/Components/Charts/MonitorDetailsAreaChart/index.jsx
- Client/src/Pages/Monitors/Details/styled.jsx
- Client/src/Pages/Monitors/utils.jsx
- Client/src/Pages/PageSpeed/Details/Charts/AreaChart.jsx
- Client/src/Pages/PageSpeed/Details/styled.jsx
- Client/src/Pages/PageSpeed/card.jsx
> Increase stroke width on hover

- Client/src/Pages/Monitors/Details/styled.jsx
> Combined transitions

- Client/src/Pages/Monitors/Home/MonitorTable/index.jsx
- Client/src/Pages/Monitors/Home/index.jsx
> Monitor table loading

- Client/src/Components/Sidebar/index.jsx
This PR fixes a hardcoded array index access
> Fixed hardcoded array access

- Client/src/Components/Sidebar/index.jsx
- Client/src/Pages/Incidents/IncidentTable/index.jsx
> Develop -> Master

- Server/package-lock.json
- Server/package.json
This PR adds the swagger-ui missing dependency
> Add swagger-ui dependency

- Server/openapi.json
> Add corrected bluewave server to swagger docs

- Client/src/Pages/Settings/index.jsx
- Server/controllers/authController.js
- Server/db/mongo/MongoDB.js
- Server/db/mongo/modules/userModule.js
This PR updates how deleting accounts is handled
> Update delete user to handle superadmin case

- docs/quickstart.md
This PR updates the documentaiton for the quick-start guide for additional clarity
> Update quickstart documentation

- Server/controllers/authController.js
- Server/controllers/checkController.js
- Server/controllers/controllerUtils.js
- Server/controllers/inviteController.js
- Server/controllers/maintenanceWindowController.js
- Server/controllers/monitorController.js
- Server/controllers/queueController.js
- Server/controllers/settingsController.js
- Server/middleware/verifyJWT.js
This PR refacotrs some the validation and general error handling in the Controllers for reduced code duplication
> Refactor BE error handling

- Client/src/Validation/validation.js
- ### Validated for negative number
- ### Validated for decimal number
> Fixes #926: Duration shouldn't be negative

- Server/tests/controllers/controllerUtils.test.js
This PR adds tests for the controller utilities
> Feat/be/controller-utils-tests, #924

- Client/src/Components/Sidebar/index.jsx
- Client/src/Pages/Settings/index.jsx
Moved theme switch toggle to settings menu.
https://github.com/user-attachments/assets/0523cc44-fb8e-426c-b902-fd9aa29db66d
Closes #934
> Fix/theme toggle position - issue#934

- Client/src/Components/TabPanels/Account/ProfilePanel.jsx
Removed edit button from profile section
[
](url)
Closes #941
> removed edit button - issue#941

- Client/src/Components/TabPanels/Account/TeamPanel.jsx
Added conditional check for null email before calling the invite function.
closes #950
> Fix: Error handling for team invite - Issue#950

- Server/package.json
This PR fixes a missing comma in pacakge.json
> Fix typo in package.json

- Server/tests/utils/dataUtils.test.js
This PR removes forgotten console.log statements from tests
> Remove log statements from

- Server/index.js
> Fixed problem with import

- Docker/prod/docker-compose.yaml
- Server/db/models/Check.js
- Server/db/models/HardwareCheck.js
- Server/db/models/PageSpeedCheck.js
Reverts bluewave-labs/bluewave-uptime#1092
> Revert "Fix/devops/docker compose"

- Client/src/Pages/Auth/Login.jsx
Removing sign up link as per issue #1180.
> Update Login.jsx to remove Sign up link

- Client/package-lock.json
- Client/package.json
- Server/package-lock.json
This PR bumps @mui packages to the latest versions
> bump mui icons to 6.1.8

- Client/src/Pages/Infrastructure/Details/index.jsx
Metrics that are missing are dispalyed as a zero value.  In the previous implementation temperature was removed entirely if it was missing, this PR updates that to replace empty data with a zero value to be consistent with the other metrics
> feat: infrasctructure details empty data handling

- Docker/prod/certbot-compose.yaml
This PR adds docker compose configs for requesting SSL certificates, it also removes an accidental duplicate config
> remove duplicate config, add certbot-compose.yaml

- Client/src/Pages/Infrastructure/index.jsx
> Add vowel start prop

- Client/src/Pages/Auth/Register/StepThree/index.jsx
This PR removes a console.log statement from step three of the Registration page
> Remove console log statement

- Client/src/Pages/Infrastructure/Details/empty.jsx
This PR updates the empty view message
> fix: infrasctrucutre details empty view message, resolves #1401

- Client/src/Pages/Uptime/Details/index.jsx
This hotfix adds a missing import statement
> add missing import

- Client/src/Utils/Theme/globalTheme.js
This PR fixes a forgotten variable rename
> neuter -> neutral

- Server/index.js
Reverts bluewave-labs/checkmate#1467
> Revert "hotfix: move middleware to after JobQueue initialization"

- Server/controllers/authController.js
- Server/controllers/checkController.js
- Server/controllers/inviteController.js
- Server/controllers/maintenanceWindowController.js
- Server/controllers/monitorController.js
- Server/controllers/queueController.js
- Server/controllers/settingsController.js
- Server/controllers/statusPageController.js
- Server/db/mongo/MongoDB.js
- Server/index.js
- Server/middleware/isAllowed.js
- Server/middleware/verifyJWT.js
- Server/middleware/verifySuperAdmin.js
- Server/routes/authRoute.js
- Server/routes/checkRoute.js
- Server/routes/inviteRoute.js
- Server/routes/maintenanceWindowRoute.js
- Server/routes/monitorRoute.js
- Server/routes/queueRoute.js
- Server/routes/settingsRoute.js
- Server/routes/statusPageRoute.js
- Server/service/emailService.js
- Server/service/jobQueue.js
- Server/service/networkService.js
- Server/service/notificationService.js
- Server/service/serviceRegistry.js
- Server/service/settingsService.js
- Server/service/statusService.js
This PR resolve an issue where registering middleware to allow access to DB and services is inconsistent, leading to hard to debug errors.  To faciliate this approach old functional routers/controllers are updated to be class based
This should make the app more stable, maintainable, and testable
> feat: be/migrate to class

- Client/src/Utils/NetworkService.js
This PR resolves a bad merge commit
> Fix bad merge commit

- Client/src/Validation/validation.js
Protocol is added to the URL at submission time, validaiton for protocol should be optional
> hotfix: make protocol optional for validation

- Client/src/Pages/Uptime/Home/index.jsx
This PR fixes incorrect use of local state for pagination, repalced with correct redux usage
> hotfix: use redux state for pagination

- Client/src/Pages/Uptime/Home/index.jsx
This PR adds a missing skeleton to the Uptime home page
> hotfix: readd skeleton

- Client/src/Pages/Uptime/Home/UptimeDataTable/index.jsx
Remove an import that should have been removed
> hotfix: remove missing import

- Client/src/Pages/Uptime/Details/Charts/DownBarChart.jsx
- Client/src/Pages/Uptime/Details/Charts/UpBarChart.jsx
- Client/src/Pages/Uptime/Details/index.jsx
- Server/db/mongo/modules/monitorModule.js
- Server/db/mongo/modules/monitorModuleQueries.js
This PR refactors the Uptime Details query as the duration calculation was not correct
> fix: be/uptime duration

- Client/src/Pages/Infrastructure/index.jsx
This PR fixes an error which prevented CPU frequency from being properly parsed.
> fix: cpu frequency parsing, resolves #1620

- Client/src/Utils/NetworkServiceProvider.jsx
Fix redundant instantiation of NetworkService
#1640
> Fix redundant instantiation of NetworkService

- Client/src/Pages/Infrastructure/Details/index.jsx
- Client/src/Pages/Infrastructure/index.jsx
- Client/src/Pages/PageSpeed/index.jsx
- Client/src/Pages/Uptime/Home/UptimeDataTable/index.jsx
- Client/src/Pages/Uptime/Home/index.jsx
> Fix some UI style/Component bugs

- Client/src/Components/Fallback/index.jsx
> Add blank space

- Client/src/Pages/Infrastructure/Details/index.jsx
- Client/src/Pages/PageSpeed/Details/index.jsx
- Client/src/Pages/Uptime/Details/index.jsx
This PR updates the empty view message for
> fix: fe/empty view message, resolves # 

- Client/src/Pages/Uptime/Configure/index.jsx
- Client/src/Pages/Uptime/Create/index.jsx
- Client/src/Validation/validation.js
- HTTP Monitor (No Error)
- HTTP Monitor (With Error)
- Docker Monitor (With Error)
- Docker Monitor (No Error)
#1666
> Fix validation error of container id

- Client/src/Components/Inputs/Search/index.jsx
- Client/src/Pages/StatusPage/Create/Hooks/useCreateStatusPage.jsx
- Client/src/Pages/StatusPage/Create/index.jsx
- Client/src/Pages/StatusPage/Status/Components/ControlsHeader/index.jsx
- Client/src/Pages/StatusPage/Status/Hooks/useStatusPageFetch.jsx
- Client/src/Pages/StatusPage/Status/index.jsx
- Client/src/Routes/index.jsx
- Client/src/Utils/NetworkService.js
- Server/controllers/statusPageController.js
- Server/db/mongo/modules/statusPageModule.js
- Server/routes/statusPageRoute.js
- Server/utils/messages.js
This PR implements configuration for status pages
> feat: fe/status page config

- Server/controllers/distributedUptimeController.js
- Server/db/models/DistributedUptimeCheck.js
- Server/db/mongo/modules/monitorModule.js
- Server/db/mongo/modules/monitorModuleQueries.js
- Server/routes/distributedUptimeRoute.js
- Server/service/jobQueue.js
- Server/service/networkService.js
- Server/service/statusService.js
This PR implemetns distributed uptime monitors on the BE
> feat: be/distributed uptime

- Client/src/Components/ProgressBars/index.jsx
Wrap long image filename
#1699
> Wrap long image filename

- Client/src/Components/ActionsMenu/index.jsx
- Client/src/Components/Host/index.jsx
- Client/src/Hooks/useMonitorUtils.js
- Client/src/Pages/DistributedUptime/Details/Components/DistributedUptimeResponseChart/index.jsx
- Client/src/Pages/DistributedUptime/Details/Components/MonitorHeader/index.jsx
- Client/src/Pages/DistributedUptime/Details/Components/StatBoxes/index.jsx
- Client/src/Pages/DistributedUptime/Details/Hooks/useSubscribeToDetails.jsx
- Client/src/Pages/DistributedUptime/Details/index.jsx
- Client/src/Pages/DistributedUptime/Monitors/Components/MonitorTable/index.jsx
- Client/src/Pages/DistributedUptime/Monitors/Hooks/useSubscribeToMonitors.jsx
- Client/src/Pages/DistributedUptime/Monitors/index.jsx
- Client/src/Pages/Infrastructure/Monitors/Components/MonitorsTable/index.jsx
- Client/src/Pages/StatusPage/Status/Components/MonitorsList/index.jsx
- Client/src/Pages/StatusPage/Status/Hooks/useStatusPageFetch.jsx
- Client/src/Pages/Uptime/Monitors/Components/UptimeDataTable/index.jsx
- Client/src/Pages/Uptime/Monitors/Hooks/useMonitorsFetch.jsx
- Client/src/Utils/NetworkService.js
This PR adds placeholders, fallbacks, and extracts components/hooks for the DU Details page
TODO
> fix: fe/du UI fixes and refactor

- Client/src/Pages/Uptime/Monitors/index.jsx
This PR updates the empty view for Uptime Monitors
> fix: update uptime fallback

- Client/src/Components/Sidebar/index.jsx
Reverts bluewave-labs/Checkmate#1749
This PR hasn't been sufficiently reviewed yet
> Revert "Fix: Sidemenu UI Overflows"

- Client/package-lock.json
- Client/src/Pages/DistributedUptime/Details/Components/DistributedUptimeResponseChart/Area/index.jsx
- Client/src/Pages/DistributedUptime/Details/Components/DistributedUptimeResponseChart/Bar/index.jsx
- Client/src/Pages/DistributedUptime/Details/Components/DistributedUptimeResponseChart/Helpers/Tick.jsx
- Client/src/Pages/DistributedUptime/Details/Components/DistributedUptimeResponseChart/Helpers/ToolTip.jsx
- Client/src/Pages/DistributedUptime/Details/Components/DistributedUptimeResponseChart/index.jsx
- Client/src/Pages/DistributedUptime/Details/index.jsx
- Server/controllers/distributedUptimeController.js
This PR adds a new bar chart for distributed uptime monitors
> feat: fe/du responsetime barchart

- Docker/dev/client.Dockerfile
- Docker/dist/client.Dockerfile
- Docker/prod/client.Dockerfile
- Docker/test/client.Dockerfile
This PR fixes a typo in the docker files.  It also increases the heap size.
> fix error in docker file

- Client/src/Features/UptimeMonitors/uptimeMonitorsSlice.js
- Client/src/Pages/Uptime/Configure/index.jsx
- Client/src/Pages/Uptime/Create/index.jsx
- Client/src/Validation/validation.js
- Server/validation/joi.js
- (Client side) Implement json validation ui in create/configure Uptime
- (Server side) Support empty string value for `expectedValue` and `jsonPath`, so that user can remove json validation by editing them to an empty value.
#1573
> Implement json validation UI

- Client/src/Components/Sidebar/index.jsx
This PR fixes the sidebar selection issue
> fix: sidebar selection, resolves #1780

- .npmrc
- README.md
> remove npmrc, copy readme

- src/locales/gb.json
Addition of monitor status messages.
n/a
> Addition of monitor status messages.

- package-lock.json
- package.json
- src/Components/InfoBox/index.jsx
- src/Components/ShareComponent/index.jsx
- src/Components/StandardContainer/index.jsx
- src/Pages/DistributedUptime/Details/Components/Chatbot/index.jsx
- src/Pages/DistributedUptime/Details/Components/DeviceTicker/index.jsx
- src/Pages/DistributedUptime/Details/Components/DistributedUptimeMap/index.jsx
- src/Pages/DistributedUptime/Details/Components/StatBoxes/index.jsx
- src/Pages/DistributedUptime/Details/Components/StatusHeader/index.jsx
- src/Pages/DistributedUptimeStatus/Status/index.jsx
- src/Utils/Theme/constants.js
This PR updates the DePIN status page to latest spec
> feat: DePIN status page

- src/Utils/NetworkService.js
This PR removes the default auth header from the Github version request.
Supplying an auth header breaks the request.
> fox: remove auth header for version request

- src/locales/gb.json
> missing strings

- src/Components/Subheader/index.jsx
- src/Pages/DistributedUptime/Details/Components/DeviceTicker/index.jsx
- src/Pages/DistributedUptime/Details/Components/DistributedUptimeMap/index.jsx
- src/Pages/DistributedUptime/Details/Components/StatBoxes/index.jsx
- src/Pages/DistributedUptime/Details/Components/StatusHeader/index.jsx
- src/Pages/DistributedUptimeStatus/Status/Components/TimeframeHeader/index.jsx
- src/Pages/DistributedUptimeStatus/Status/index.jsx
- src/Utils/utils.js
This PR makes the status page display properly on small screens:
> feat: make status page responsive

- src/Components/Subheader/index.jsx
- src/Pages/DistributedUptimeStatus/Status/index.jsx
This PR adds a `shouldRender` prop to `SubHeader` to control conditional rendering
> feat: conditionally render subheader

- src/Pages/DistributedUptime/Details/Components/DeviceTicker/index.jsx
- src/Pages/StatusPage/Status/Components/ControlsHeader/index.jsx
This PR updates the responsive status page design
> feat: status page update

- src/Pages/DistributedUptimeStatus/Status/index.jsx
- src/locales/gb.json
- src/locales/tr.json
This PR replaces placeholder data with correct data
> feat: set monitor name instead of placeholder data

- src/Pages/DistributedUptime/Monitors/Hooks/useSubscribeToMonitors.jsx
- src/Pages/DistributedUptime/Monitors/index.jsx
- src/Pages/StatusPage/StatusPages/index.jsx
This PR adds missing pagination to DePIN monitors table
> feat: add pagination to DePIN Monitors

- src/Components/Charts/CustomGauge/index.jsx
- src/Components/StatBox/index.jsx
- src/Pages/Infrastructure/Details/Components/GaugeBoxes/Gauge.jsx
- src/Pages/Infrastructure/Details/Hooks/useHardwareUtils.jsx
- src/Pages/Infrastructure/Details/index.jsx
- src/Utils/Theme/constants.js
- I fixed a typo on the infrastructure details page.
- Toned down the gradient of stat boxes to improve readability and reduce eye strain.
- Implemented the custom gauge design to match the Figma specifications.
#1291 
https://github.com/user-attachments/assets/3ba7bfe7-3f80-4211-924f-a4587d3abbd7
> Fix: Infrastructure Details Page Design

- src/Pages/DistributedUptime/Monitors/Hooks/useSubscribeToMonitors.jsx
- src/Utils/NetworkService.js
This PR adds an initial data fetch operatoin to the DePIN fetch monitors hook.
> feat: depin monitors initial data fetch, #1867

- src/Components/Sidebar/index.jsx
- src/Pages/DistributedUptime/Details/Hooks/useSubscribeToDetails.jsx
- src/Utils/NetworkService.js
This PR adds an initial data fetch via regular HTTP GET request as the SSE handshake takes some time
> feat: depin details initial data

- src/Pages/DistributedUptime/Details/Components/DistributedUptimeResponseChart/Helpers/ToolTip.jsx
- src/Pages/DistributedUptime/Details/Components/StatBoxes/index.jsx
This PR refactors to use MonitorStats to improve query performance
> feat: refactor to use monitor-stats

- src/Pages/DistributedUptime/Details/Components/DistributedUptimeMap/index.jsx
Update Map data access to use improved map query
> feat:use simplified map query

- src/Pages/Auth/Register/Register.jsx
Stringified "token" object that is saved in local storage, as it's currently stored as string.
https://github.com/bluewave-labs/Checkmate/issues/1894
> fix: stringify token upon registration

- .github/scripts/download-translations.js
- .github/workflows/poeditor-sync.yml
> fix: use require

- .github/workflows/first-issue-first-pr.yml
This uses https://github.com/marketplace/actions/first-interaction to create a message for first issuers/PR holders.
> Create a workflow for first issue/pr.

- src/Pages/DistributedUptime/Details/Components/StatusHeader/index.jsx
- src/Pages/StatusPage/Status/index.jsx
This PR fixes uptime percentage
> fix uptime percentage

- src/Components/Inputs/Search/index.jsx
- src/Components/Link/index.jsx
- src/Utils/Theme/globalTheme.js
For error to be in error.main color and text should not be wrapped in order to show the complete error.
#1848
Before:
After:
> Error wrap maintenance page

- src/Components/Inputs/Search/index.jsx
Made the bg and color of list items according to the other themes in app.
#1907
https://github.com/user-attachments/assets/a1855835-c5d5-4a8e-b75f-35e9ab3ba60c
https://github.com/user-attachments/assets/395f2780-abca-4cd5-9335-75f521817c04
> FIX-1907 drop downs are of common color now.

- .github/scripts/upload-translations.js
- .github/workflows/README.md
- .github/workflows/first-issue-first-pr.yml
- .github/workflows/upload-poeditor.yml
- src/locales/tr.json
We have successfully created a GitHub Actions workflow that automatically uploads translation files to POEditor when changes are merged to the develop branch. Here's a summary of what we've implemented:
1. .github/scripts/upload-translations.js
- A Node.js script that handles the upload of translation files to POEditor
- Uses the POEditor API to upload JSON translation files
- Validates file existence and JSON format before uploading
- Provides detailed logging of the upload process
2. .github/workflows/poeditor-upload-on-merge.yml - A GitHub Actions workflow that triggers when PRs are merged to the develop branch - Only runs when changes are made to files in the src/locales directory - Detects which translation files were changed in the PR - Extracts language codes from filenames (e.g., …
> Upload poeditor

- .github/workflows/upload-poeditor.yml
- src/locales/tr.json
> Fix workflow typo

- .github/scripts/download-translations.js
- .github/workflows/poeditor-sync.yml
- src/locales/tr.json
> Open pull request for translations

- src/Components/ConfigRow/index.jsx
- src/Pages/Maintenance/CreateMaintenance/Components/ConfigRow/index.jsx
- src/Pages/Maintenance/CreateMaintenance/Components/MonitorsConfig/index.jsx
I restructured the "Create Maintenance - Monitor section" by breaking it into smaller, independent component. Each row will now wrapped in a common component to maintain consistent UI design. This change improves readability, debugging, and allows for better component organisation.
#1930 
- [] I have added i18n support to visible strings (instead of `<div>Add</div>`, use): 
```Javascript
```
- [] I took a screenshot or a video and attached to this PR if there is a UI change.
> FIX-1930 have made initial changes in order to proceed with rebuilding.

- src/Components/Inputs/Search/index.jsx
we had faced a issue where the backend api was not returning an object which consists of a key called "type" but instead the UI was defining it as undefined for end user (confusing for them)
#1913 
```Javascript
```
- [ x I made sure font sizes, color choices etc are all referenced from the theme. I have no hardcoded dimensions.
- [] I took a screenshot or a video and attached to this PR if there is a UI change.
> Fixed the check for the label in options object in search component

- src/Utils/Theme/constants.js
This PR sets the base font size to 13px
> fix: adjust typography base font size

- src/Pages/Uptime/Create/index.jsx
This PR fixes an incorrectly handled merge conflict resoluton that reuslted in duplicate imports.
> fix: bad merge

- src/Pages/Uptime/Details/Components/ChartBoxes/index.jsx
This PR fixes incorrect nullish coallescing
> fix: nullish coallescing for uptime percetnage

- src/Pages/Uptime/Details/Components/ChartBoxes/index.jsx
- src/Pages/Uptime/Details/Components/Charts/UpBarChart.jsx
- src/Pages/Uptime/Details/Hooks/useChecksFetch.jsx
- src/Pages/Uptime/Details/index.jsx
This PR normalizes data for the uptime charts in the Uptime Details page
> fix: normalize data for charts

- src/Hooks/useSubscribeToDepinMonitors.js
- src/Pages/Maintenance/index.jsx
- src/Pages/Settings/index.jsx
- src/Utils/NetworkService.js
This PR renders network error views if an error occurs
> fix: handle jwt errors

- src/Components/Fallback/index.jsx
- src/Components/Layouts/HomeLayout/index.css
- src/Components/Layouts/HomeLayout/index.jsx
- src/Components/Sidebar/index.jsx
- src/Pages/Uptime/Monitors/Components/UptimeDataTable/index.jsx
- src/Utils/Theme/constants.js
- Changed the sidebar position to keep fixed to left of screen 
- Added subtle tint to sidebar background color 
- Fixed layout alignment issues
```Javascript
```
Before:
After:
Recording:
https://github.com/user-attachments/assets/925dc269-3bdd-4b46-8c98-72898ba7f2e1
> Modify Sidebar UI

- src/Utils/NetworkService.js
This PR fixes a conditional to redirect to login on 401 error (unauthorized access)
> fix: redirect to login on invalid token

- src/Pages/Uptime/Configure/index.jsx
- src/Pages/Uptime/Create/index.jsx
- src/Utils/NetworkService.js
This PR addresses two key issues in the Uptime monitoring feature:
1. Fixed Monitor Configuration Saving
- Added missing fields (matchMethod, expectedValue, jsonPath) to NetworkService.updateMonitor
- Ensures configuration changes persist when editing existing monitors
2. Improved Field Examples
- Updated JSON Path placeholder to "data.status" (from "data.email")
- Updated Expected Value placeholders to match common API status patterns:
Equal: "success"
Include: "ok"
Regex: "^(success|ok)$"
```Javascript
```
> Improve Uptime Monitor Configuration

- src/Pages/StatusPage/Create/Components/Tabs/index.jsx
- src/Utils/Theme/globalTheme.js
- Fix the styling of tabs in status pages > create/config pages
- Now it has the same design as the tabs in accounts page
```Javascript
```
Before:
After:
> Fix status page tab styling

- src/Components/FilterHeader/index.jsx
- src/locales/gb.json
This PR address minor UI fixes in filters.
```Javascript
```
> Fix: Minor UI Fix in Filters

- src/Components/Sidebar/index.jsx
- src/Components/Table/index.jsx
This PR address the minor UI fixes in uptime table headers and sidebar header.
```Javascript
```
> Fix: Uptime UI Fixes

- src/Components/MonitorCountHeader/index.jsx
- src/Pages/Infrastructure/Monitors/index.jsx
- src/Pages/PageSpeed/Monitors/index.jsx
- src/Pages/Uptime/Monitors/index.jsx
This PR introduces a new monitor header UI designed to enhance user experience and improve the overall UI.
```Javascript
```
> Feat: New Monitor Header UI

- src/Components/Sidebar/index.jsx
closes issue https://github.com/bluewave-labs/Checkmate/issues/2037
Describe your changes:
This PR addresses the side menu functionality - it doesn't close after click
Please ensure all items are checked off before requesting a review. "Checked off" means you need to add an "x" character between brackets so they turn into checkmarks.
[x] (Do not skip this or your PR will be closed) I deployed the application locally.
[x] (Do not skip this or your PR will be closed) I have performed a self-review and testing of my code.
[x]  I have included the issue # in the PR.
[x] I took a screenshot or a video and attached to this PR if there is a UI change.
[x] My PR is granular and targeted to one specific feature.
[x] The issue I am working on is assigned to me. …
> Fix. :side menu close on click

- src/Components/Charts/ChartBox/index.jsx
- src/Pages/Infrastructure/Monitors/Components/MonitorsTable/index.jsx
Changed the color from a low contrast color to main as it was before.
- [] I have included the issue # in the PR.
```Javascript
```
New UI of charts
> FIX in the charts background color to main instead of a low contrast.

- src/Components/Tab/index.jsx
- src/Pages/Account/index.jsx
- src/Pages/StatusPage/Create/Components/Tabs/index.jsx
- src/Utils/Theme/globalTheme.js
- Created a `CustomTabList` component to standardize tab styling across the application
- Removed background color and borders for the tab
#2036 
```Javascript
```
> Unify tab styles with CustomTabList component

- src/Pages/Uptime/Create/index.jsx
FIX:  This PR uncomments out the code for adding notificiations to a monitor on creation
```Javascript
```
> uncomment out notificiations

- src/Components/FilterHeader/index.jsx
- src/Utils/Theme/globalTheme.js
- src/locales/gb.json
This PR implements a new UI for Filters.
```Javascript
```
> Feat: Filters UI

- src/Components/FilterHeader/index.jsx
- src/Pages/Infrastructure/Monitors/Components/Filters/index.jsx
- src/Pages/Infrastructure/Monitors/Hooks/useMonitorFetch.jsx
- src/Pages/Infrastructure/Monitors/index.jsx
- src/Pages/Uptime/Monitors/Components/Filter/index.jsx
This PR implements the filtering functionality in the infra monitors page.
```Javascript
```
> Feat: Infra Monitors Filters

- .github/workflows/staging-deploy.yml
- docker/staging/client.Dockerfile
This PR adds a Github action to deploy to staging server
> feat: add dockerfile and action

- client/env.sh
> add env.sh

- docker/staging/docker-compose.yaml
- docker/staging/mongo/init/init_replica_set.js
Replica set was not initialized if one did not exist.  This PR adds a script to initialize
> feat: init replica set

- .github/workflows/production-deploy.yml
> add manual dispatch

- docker/prod/mongo/init/init.js
> corrected script

- docker/prod/docker-compose.yaml
- docker/prod/mongo/init/init.js
- docker/staging/docker-compose.yaml
Add replica set initiailzation to health check for MongoDB container
> fix: prod docker

- .github/workflows/distribution-deploy.yml
- docker/dist/docker-compose.yaml
This PR adds a workflow to build images and push to Github Container Repository on push to master
It also updates the docker compose file
> feat: release workflow

- docker/prod/docker-compose.yaml
> mount docker socket

- .github/workflows/production-deploy.yml
- .github/workflows/staging-deploy.yml
This PR adds a `git pull` operation to the repos before running
> fix: add git pull to staging and produciton deploy workflows

- client/src/Components/NotificationIntegrationModal/Components/NotificationIntegrationModal.jsx
This PR fixes a bug wherein a `useCallback` hook was not supplied iwth a dependency array leading to a render loop
> hotfix: missing dependency array

- client/src/Features/PageSpeedMonitor/pageSpeedMonitorSlice.js
- client/src/Pages/PageSpeed/Monitors/index.jsx
- server/controllers/monitorController.js
This PR fixes some issues with Pagespeed configuraiton
> hotfix: pagespeed monitors config

- docker/dist/docker-compose.yaml
- docker/prod/docker-compose.yaml
- docker/staging/docker-compose.yaml
> fix: add client-host

- client/src/Hooks/inviteHooks.js
This PR corrects an env var name
> fix env var name

- docker/dev/build_images.sh
- docker/dev/client.Dockerfile
- docker/dev/docker-compose.yaml
- docker/dev/nginx/conf.d/default.conf
This PR fixes the docker configuration.  Two required values were missing from .env.production which is required for interpolating env vars at runtime.
> update .env.produciton, update dev docker build

- client/src/Pages/Settings/index.jsx
- docker/dev/docker-compose.yaml
- docker/dev/nginx/conf.d/default.conf
- docker/dev/server.Dockerfile
- docker/dist/server.Dockerfile
- docker/prod/docker-compose.yaml
- docker/prod/nginx/conf.d/default.conf
- docker/prod/server.Dockerfile
- docker/staging/docker-compose.yaml
- docker/staging/nginx/conf.d/default.conf
- docker/staging/server.Dockerfile
- server/controllers/settingsController.js
- server/db/models/AppSettings.js
- server/db/mongo/MongoDB.js
- server/db/mongo/modules/settingsModule.js
- server/index.js
- server/service/settingsService.js
This PR updates the default port for the server to 52345
> fix: default server port

- client/src/Pages/Uptime/Monitors/Components/StatusBoxes/index.jsx
Status box labels should not be upper case
> hotfix:remove toUpperCase

- client/src/Pages/StatusPage/Create/index.jsx
- client/src/Utils/Theme/globalTheme.js
> hotfix: remove font offset

- client/src/locales/gb.json
> hotfix: bad conflict resolution

- client/src/locales/gb.json
Monitor status values must be lower case strings
> hotfix: monitor status values

- docker/dist/docker-compose.yaml
This PR amends the port for the docker compose dist file
> fix: ammend base url for dist version

- client/src/Components/Alert/index.jsx
- client/src/Components/Fallback/index.jsx
- docker/dist/docker-compose.yaml
This PR updates the Pagespeed fallback so it actually checks if an API key has been set
> hotfix: conditionally render alert based on settings

- docker/dist/build_images.sh
This PR adds mutli-arch support using docker buildx.  AMD64 and ARM64 should both be supported
> feat: build multi-arch images for dist

- client/src/Pages/Uptime/Details/Components/ChartBoxes/index.jsx
This PR fixes a logical error in displaying uptine percentage
> hotfix: uptime-percentage

- .github/workflows/distribution-deploy.yml
- .github/workflows/distribution-mono-deploy.yml
- docker/.gitignore
- docker/dist-mono/build_images.sh
- docker/dist-mono/docker-compose.yaml
- docker/dist-mono/mongoDB.Dockerfile
- docker/dist-mono/redis.Dockerfile
- docker/dist-mono/server.Dockerfile
- server/index.js
This PR adds a new docker config to server the client from the server instead of a separate nginx server
> fix: monolithic docker

- client/src/Components/MonitorDetailsControlHeader/index.jsx
- server/service/emailService.js
This PR fixes an issue with test emails
A funciton was inocrrectly invoked and a db call was not awaited
> fix: test email

- server/service/notificationService.js
This PR adds a missing config for webhook notifications
> fix: add config for webhook

- docker/dist/docker-compose.yaml
`checkmate-frontend` -> `checkmate-client`
> hotfix: image name

- client/src/Pages/Incidents/Components/IncidentTable/index.jsx
- client/src/Pages/Incidents/index.jsx
- client/src/Utils/NetworkService.js
- server/controllers/checkController.js
- server/db/mongo/modules/checkModule.js
- server/routes/checkRoute.js
- server/validation/joi.js
This PR removes teamId from check requests and uses the teamID in the JWT.
It also standardizes DB request methods
> fix: checks team

- client/src/Hooks/monitorHooks.js
- client/src/Hooks/useNotifications.js
- client/src/Pages/Incidents/index.jsx
- client/src/Pages/Infrastructure/Create/index.jsx
- client/src/Pages/Notifications/create/index.jsx
- client/src/Pages/PageSpeed/Create/index.jsx
- client/src/Pages/Settings/index.jsx
- client/src/Pages/StatusPage/Create/Hooks/useCreateStatusPage.jsx
- client/src/Pages/StatusPage/StatusPages/Hooks/useStatusPagesFetch.jsx
- client/src/Pages/Uptime/Create/index.jsx
- client/src/Utils/NetworkService.js
- server/controllers/monitorController.js
- server/controllers/statusPageController.js
- server/db/mongo/modules/monitorModule.js
- server/db/mongo/modules/statusPageModule.js
- server/routes/statusPageRoute.js
- server/validation/joi.js
This PR removes userId and teamId from frontend requests and fetches it from `req.user` instead
> fix: remove team and user

- server/service/networkService.js
`requestPing` was broken by a refacotr, this PR updates the method to function properly.
It also adds a `name` prop to the `radio` component in order to function properly
> hotfix: ping monitoring

- client/src/Components/Inputs/Radio/index.jsx
- client/src/Pages/Uptime/Create/index.jsx
This PR adds the `name` prop to the radio component
> hotfix: add name prop to radio component

- client/package-lock.json
- client/package.json
- client/src/Hooks/logHooks.js
- client/src/Pages/Logs/Logs/index.jsx
- client/src/Pages/Logs/Queue/components/Metrics/index.jsx
- client/src/Pages/Logs/index.jsx
- client/src/Utils/NetworkService.js
- client/src/assets/icons/logs.svg
- client/src/locales/en.json
- server/controllers/logController.js
- server/index.js
- server/routes/logRoutes.js
- server/utils/logger.js
This PR adds a logs component to the logs page
> feat: logs

- client/src/Utils/Theme/constants.js
> fix: update bg color

- client/src/Components/MonitorCreateHeader/index.jsx
Comment out feature not ready for release
> fix: temporarliy comment out import/export

- docker/.gitignore
- docker/dist-arm/docker-compose.yaml
- docker/dist-mono/docker-compose.yaml
- docker/dist/docker-compose.yaml
Update docker compose files for upcoming release
> feat: update docker compose

- server/controllers/authController.js
> add missing  context

- server/controllers/authController.js
> hotfix: add missing contenxt

- server/db/mongo/modules/checkModule.js
- server/db/mongo/modules/diagnosticModule.js
- server/db/mongo/modules/monitorModule.js
- server/db/mongo/modules/monitorModuleQueries.js
- server/db/mongo/modules/statusPageModule.js
This PR removes Mongo features that are not compatible with MongoDB v4.4
> fix: donwgrade mongo functions

- client/src/Pages/Notifications/create/index.jsx
- client/src/locales/en.json
This PR adds a confirmation dialog to the delete notification page
> feat: add delete confirmation dialog to notificiaton page

- server/routes/checkRoute.js
Route specificity was incorrect for the check router
> fix: reorder rotues to correctly match

- server/controllers/checkController.js
- server/routes/checkRoute.js
This PR updates authentication handling for check routes
> fix auth for check routes

- server/controllers/diagnosticController.js
- server/routes/diagnosticRoute.js
This PR removes unused routes and adds auth to the remaining diagnostic route
> fix: remove unused routes, add authentication

- server/controllers/maintenanceWindowController.js
- server/db/mongo/modules/maintenanceWindowModule.js
- server/db/mongo/modules/monitorModule.js
- server/index.js
- server/routes/maintenanceWindowRoute.js
Add team validaiton checks to maintenane window routes
> fix: mw routes

- client/src/Utils/NetworkService.js
- server/controllers/monitorController.js
- server/db/mongo/modules/monitorModule.js
- server/routes/monitorRoute.js
> fix: monitor routes

- server/controllers/authController.js
This PR adds a check that prevents users with "demo" role from being deleted
> prevent demo user from being deleted

- server/controllers/diagnosticController.js
- server/index.js
- server/service/business/diagnosticService.js
This PR moves business logic from controller to service
> feat: diagnostic service

- server/controllers/inviteController.js
- server/controllers/maintenanceWindowController.js
- server/index.js
- server/service/business/maintenanceWindowService.js
This PR moves logic from controller to service
> feat: add maintenance window service

- client/src/Pages/Uptime/Create/index.jsx
Clone monitor funcitonality was removed some time ago.  This PR adds a quick fix, to be refactored.
> fix: reimplement clone monitor, resolves #2676

- server/src/config/services.js
- server/src/db/mongo/MongoDB.js
- server/src/db/mongo/modules/networkCheckModule.js
This PR converts the NetworkCheck module to a class
> feat: NetworkCheck module -> class

- server/src/config/services.js
- server/src/db/mongo/MongoDB.js
- server/src/db/mongo/modules/pageSpeedCheckModule.js
- server/src/service/business/monitorService.js
- server/src/service/infrastructure/bufferService.js
This PR converts the pagespeed module to a class
> feat: pagespeed module->class

- client/vite.config.js
> fix: bump version

- server/src/service/system/translationService.js
String service locales path was broken.
> fix: string service path, resolves #2847, resolves #2848

- client/vite.config.js
- docker/coolify/client.Dockerfile
- docker/coolify/server.Dockerfile
- docker/dev/client.Dockerfile
- docker/dev/server.Dockerfile
- docker/dist-arm/server.Dockerfile
- docker/dist-mono/server.Dockerfile
- docker/dist/client.Dockerfile
- docker/dist/server.Dockerfile
- docker/prod/client.Dockerfile
- docker/prod/server.Dockerfile
- docker/staging/client.Dockerfile
- docker/staging/server.Dockerfile
Move from Alpine to Slim for compatibility
> alpine -> slim

- client/package.json
- docker/dist-arm/server.Dockerfile
- docker/dist-mono/server.Dockerfile
Reverts bluewave-labs/Checkmate#2911
> Revert "develop->master"

- server/package-lock.json
- server/package.json
> bump scheduler

- client/vite.config.js
- docker/coolify/server.Dockerfile
- docker/dev/server.Dockerfile
- docker/dist-arm/server.Dockerfile
- docker/dist-mono/server.Dockerfile
- docker/dist/server.Dockerfile
- docker/prod/server.Dockerfile
- docker/staging/server.Dockerfile
This PR adds ping to the node:slim images used for all builds
> fix: install ping

- client/vite.config.js
- docker/dist-arm/server.Dockerfile
- docker/dist-mono/docker-compose.yaml
- docker/dist-mono/server.Dockerfile
Ping was installed during the client build phase instead of server build phase.
> fix: mono dist ping
